Repository DLR-AMR/t8code, pull requests merged in 2022-08, with the labels that each got.

#291 Update pull_request_template.md
  pull_request_template.md
Labels: next release

#304 Extending C element interface.
  src/t8_element_c_interface.cxx
  src/t8_element_c_interface.h
  src/t8_element_cxx.hxx
Labels: enhancement, shouldn't take long, next release

#308 Enhance pyramid element
  src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.cxx
  src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.hxx
  src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.c
  src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.h
Labels: enhancement, documentation

#312 Reduce maxlvl in t8_test_find_parent
  test/t8_schemes/t8_test_find_parent.cxx
Labels: shouldn't take long, tests

#113 Feature brep geometry
  .github/workflows/tests.yml
  Makefile.am
  benchmarks/time_forest_partition.cxx
  config/t8_include.m4
  config/t8_occ.m4
  example/IO/cmesh/gmsh/t8_load_and_refine_square_w_hole.cxx
  example/IO/cmesh/gmsh/t8_read_msh_file.cxx
  example/IO/cmesh/t8_cmesh_load_save.cxx
  example/advect/make_channel.geo
  example/advect/t8_advection.cxx
  example/common/t8_example_common.h
  example/common/t8_example_common_functions.cxx
  example/forest/t8_test_face_iterate.cxx
  example/forest/t8_test_ghost.cxx
  example/forest/t8_test_ghost_large_level_diff.cxx
  example/geometry/Makefile.am
  example/geometry/make_naca6412.geo
  example/geometry/t8_example_geometries.cxx
  example/geometry/t8_occ_naca.cxx
  src/Makefile.am
  src/t8_cmesh/t8_cmesh_occ.cxx
  src/t8_cmesh/t8_cmesh_occ.hxx
  src/t8_cmesh/t8_cmesh_readmshfile.c
  src/t8_cmesh/t8_cmesh_readmshfile.cxx
  src/t8_cmesh/t8_cmesh_types.h
  src/t8_cmesh_readmshfile.h
  src/t8_eclass.c
  src/t8_eclass.h
  src/t8_forest.h
  src/t8_forest/t8_forest.c
  src/t8_forest/t8_forest_types.h
  src/t8_geometry/t8_geometry_helpers.c
  src/t8_geometry/t8_geometry_helpers.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.hxx
  test/Makefile.am
  test/t8_cmesh/t8_test_cmesh_readmshfile.cxx
  test/t8_geometry/t8_gtest_geometry_occ.cxx
  test/t8_gtest_occ_linkage.cxx
Labels: next release

#313 Enable less tests for pull requests
  .github/workflows/tests.yml
Labels: CI

#316 Write the global tree id when linked with vtk
  src/t8_forest/t8_forest_vtk.cxx
Labels: shouldn't take long

#320 Update README.md
  README.md
Labels: shouldn't take long, next release, Readme

#322 Updating links in doxygen landing page.
  doc/mainpage.dox
Labels: shouldn't take long, documentation, next release

#319 fix in linear id for level < t->level
  src/t8_schemes/t8_default/t8_default_tri/t8_dtri_bits.c
Labels: bug, shouldn't take long, next release

#323 Update README.md
  tutorials/README.md
Labels: shouldn't take long
