Repository DLR-AMR/t8code, pull requests merged in 2022-11, with the labels that each got.

#359 Updated class parameters to coding guideline, one line per variable
  test/t8_schemes/t8_gtest_init_linear_id.cxx
Labels: enhancement, shouldn't take long, tests

#361 Added files to `.gitignore` which are generated via `./bootstrap`.
  .gitignore
Labels: enhancement, shouldn't take long

#348 Pyramid: compute and use switch_shape_at_level
  src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.cxx
  src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.c
  src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.h
Labels: enhancement

#360 updated test_hypercube to gtest_hypercube
  doc/author_weber.txt
  test/Makefile.am
  test/t8_cmesh/t8_gtest_hypercube.cxx
  test/t8_cmesh/t8_test_hypercube.c
Labels: tests

#364 Enhancement test to gtest
  test/Makefile.am
  test/t8_cmesh/t8_gtest_cmesh_copy.cxx
  test/t8_cmesh/t8_test_cmesh_copy.c
Labels: tests

#367 Added more information to error message
  src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.cxx
Labels: enhancement, shouldn't take long
