Repository DLR-AMR/t8code, pull requests merged in 2022-04, with the labels that each got.

#197 Create mattermost.yml
  .github/workflows/mattermost.yml
Labels: enhancement, New feature, CI

#196 Update gtest output
  Makefile.am
Labels: enhancement, tests

#221 Add a doxygen mainpage
  doc/mainpage.dox
Labels: documentation

#223 Feature nca test
  test/Makefile.am
  test/t8_gtest_nca.cxx
Labels: enhancement, tests
