Repository DLR-AMR/t8code, pull requests merged in 2022-07, with the labels that each got.

#273 Update Readme
  README.md
Labels: shouldn't take long, documentation, next release

#278 Feature recursive nca testing
  test/t8_schemes/t8_gtest_nca.cxx
Labels: enhancement, tests

#280 Feature nca for pyramids
  src/t8_forest/t8_forest_iterate.cxx
  src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.cxx
  src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.hxx
  src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.c
  src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.h
  src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_connectivity.c
  src/t8_schemes/t8_default/t8_default_tri/t8_dtri_bits.c
  test/t8_schemes/t8_gtest_nca.cxx
Labels: enhancement

#270 Feature connectivity tests
  src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_connectivity.c
  test/Makefile.am
  test/t8_schemes/t8_gtest_pyra_connectivity.cxx
Labels: tests, next release

#274 Feature doc schemes
  src/t8_element_c_interface.h
  src/t8_element_cxx.hxx
  src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.hxx
  src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.hxx
  src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.hxx
  src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.hxx
  src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.hxx
  src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.hxx
  src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.hxx
  src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.hxx
Labels: enhancement, documentation, next release

#296 Feature replace p4est macros
  example/IO/cmesh/gmsh/t8_load_and_refine_square_w_hole.cxx
  example/IO/cmesh/gmsh/t8_read_msh_file.cxx
  example/IO/cmesh/tetgen/t8_forest_from_tetgen.cxx
  example/IO/cmesh/tetgen/t8_read_tetgen_file.c
  example/IO/cmesh/tetgen/t8_time_tetgen_file.c
  example/IO/cmesh/triangle/t8_read_triangle_file.cxx
  example/forest/t8_test_ghost_large_level_diff.cxx
  src/t8.c
  src/t8.h
  src/t8_cmesh.h
  src/t8_cmesh/t8_cmesh_examples.c
  src/t8_cmesh/t8_cmesh_examples.h
  test/t8_cmesh/t8_test_cmesh_copy.c
  test/t8_cmesh/t8_test_cmesh_face_is_boundary.cxx
  test/t8_cmesh/t8_test_cmesh_partition.cxx
  test/t8_cmesh/t8_test_cmesh_readmshfile.c
  test/t8_cmesh/t8_test_hypercube.c
  test/t8_data/t8_test_shmem.cxx
  test/t8_forest/t8_test_element_general_function.cxx
  test/t8_forest/t8_test_find_owner.cxx
  test/t8_forest/t8_test_forest_commit.cxx
  test/t8_forest/t8_test_ghost_and_owner.cxx
  test/t8_forest/t8_test_ghost_exchange.cxx
  test/t8_forest/t8_test_half_neighbors.cxx
  test/t8_forest/t8_test_search.cxx
  test/t8_forest/t8_test_transform.cxx
  test/t8_forest/t8_test_user_data.cxx
  test/t8_geometry/t8_test_geometry.cxx
  test/t8_geometry/t8_test_point_inside.cxx
  test/t8_gtest_main.cxx
  test/t8_schemes/t8_test_descendant.cxx
  test/t8_schemes/t8_test_element_count_leafs.cxx
  test/t8_schemes/t8_test_find_parent.cxx
  test/t8_schemes/t8_test_init_linear_id.cxx
  test/t8_schemes/t8_test_pyra_face_descendant.cxx
  test/t8_schemes/t8_test_pyra_face_neigh.cxx
  test/t8_schemes/t8_test_successor.cxx
Labels: enhancement, next release

#301 Use tabs in .gitmodule file to align text
  .gitmodules
Labels: shouldn't take long

#302 Update Source name in makefile
  example/IO/cmesh/netcdf/Makefile.am
Labels: bug, examples, shouldn't take long
