Repository DLR-AMR/t8code, pull requests merged in 2023-02, with the labels that each got.

#419 Adding step6 tutorial.
  tutorials/Makefile.am
  tutorials/general/t8_step6.h
  tutorials/general/t8_step6_main.cxx
  tutorials/general/t8_step6_stencil.cxx
Labels: examples, Wiki, good first issue, documentation

#366 Test cmesh face is boundary
  test/Makefile.am
  test/t8_cmesh/t8_gtest_cmesh_face_is_boundary.cxx
  test/t8_cmesh/t8_test_cmesh_face_is_boundary.cxx
Labels: enhancement, tests

#440 Update indent script
  scripts/find_all_source_files.scp
  tutorials/features/t8_features_curved_meshes.cxx
  tutorials/general/t8_step6_stencil.cxx
Labels: bug, shouldn't take long

#436 remove outdated TODO comment
  src/t8_cmesh/t8_cmesh_commit.c
Labels: cleanup
