Repository DLR-AMR/t8code, pull requests merged in 2023-11, with the labels that each got.

#808 More const params
  src/t8.c
  src/t8.h
  src/t8_forest/t8_forest.c
  src/t8_forest/t8_forest_cxx.cxx
  src/t8_forest/t8_forest_general.h
  src/t8_forest/t8_forest_ghost.cxx
  src/t8_forest/t8_forest_ghost.h
Labels: enhancement, shouldn't take long

#842 This Todo does not refer to a function anymore.
  src/t8_cmesh.h
Labels: shouldn't take long, cleanup

#843 Gave the adapt function a more explaining name
  example/forest/t8_test_ghost.cxx
Labels: shouldn't take long, cleanup

#837 Remove todo
  src/t8_cmesh/t8_cmesh_examples.c
  src/t8_cmesh/t8_cmesh_examples.h
Labels: shouldn't take long, cleanup

#844 Delete element boundaries
  src/t8_element_c_interface.h
  src/t8_element_cxx.hxx
  src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.cxx
  src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.hxx
  src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.hxx
  src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.hxx
  src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.hxx
  src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.cxx
  src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.hxx
  src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.cxx
  src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.hxx
  src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.cxx
  src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.hxx
  src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.hxx
Labels: enhancement, shouldn't take long, cleanup

#848 Fixed TODO for code duplication in t8_cmesh_examples.c
  src/t8_cmesh/t8_cmesh_examples.c
Labels: shouldn't take long, cleanup

#833 Feature issue28 get element return const
  example/advect/t8_advection.cxx
  example/forest/t8_test_face_iterate.cxx
  src/t8_forest/t8_forest.c
  src/t8_forest/t8_forest_balance.cxx
  src/t8_forest/t8_forest_cxx.cxx
  src/t8_forest/t8_forest_general.h
  src/t8_forest/t8_forest_iterate.cxx
  src/t8_forest/t8_forest_netcdf.cxx
  src/t8_forest/t8_forest_partition.cxx
  test/t8_forest/t8_gtest_ghost_exchange.cxx
  test/t8_forest/t8_gtest_half_neighbors.cxx
  test/t8_forest_incomplete/t8_gtest_iterate_replace.cxx
  test/t8_schemes/t8_gtest_element_ref_coords.cxx
  tutorials/general/t8_step6_stencil.cxx
Labels: enhancement

#853 Element equality assertion in google-test style
  src/t8_element_c_interface.cxx
  src/t8_element_c_interface.h
  src/t8_element_cxx.hxx
  src/t8_schemes/t8_default/t8_default_common/t8_default_common_cxx.cxx
  src/t8_schemes/t8_default/t8_default_common/t8_default_common_cxx.hxx
  src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.cxx
  src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.hxx
  src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.cxx
  src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.hxx
  src/t8_schemes/t8_default/t8_default_line/t8_dline_bits.c
  src/t8_schemes/t8_default/t8_default_line/t8_dline_bits.h
  src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.cxx
  src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.hxx
  src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.c
  src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.h
  src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.cxx
  src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.hxx
  src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.c
  src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.h
  src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.cxx
  src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.hxx
  src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.cxx
  src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.hxx
  src/t8_schemes/t8_default/t8_default_tet/t8_dtet_bits.h
  src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.cxx
  src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.hxx
  src/t8_schemes/t8_default/t8_default_tri/t8_dtri_bits.c
  src/t8_schemes/t8_default/t8_default_tri/t8_dtri_bits.h
  src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.cxx
  src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.hxx
  test/Makefile.am
  test/t8_forest/t8_gtest_half_neighbors.cxx
  test/t8_forest/t8_gtest_search.cxx
  test/t8_forest/t8_gtest_transform.cxx
  test/t8_gtest_custom_assertion.hxx
  test/t8_schemes/t8_gtest_ancestor.cxx
  test/t8_schemes/t8_gtest_descendant.cxx
  test/t8_schemes/t8_gtest_face_descendant.cxx
  test/t8_schemes/t8_gtest_face_neigh.cxx
  test/t8_schemes/t8_gtest_find_parent.cxx
  test/t8_schemes/t8_gtest_nca.cxx
  test/t8_schemes/t8_gtest_successor.cxx
Labels: enhancement, Follow-up PR

#850 Update cmesh partition alternative sendrecv range
  src/t8_cmesh/t8_cmesh_partition.c
Labels: enhancement, shouldn't take long, cleanup

#856 Add include_guards
  test/t8_gtest_custom_assertion.hxx
Labels: shouldn't take long, critical

#836 Fix prism extrude face return value
  src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.cxx
  src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.c
  src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.h
Labels: shouldn't take long, cleanup

#859 Fix interface
  test/t8_schemes/t8_gtest_dfs_base.hxx
  test/t8_schemes/t8_gtest_equal.cxx
Labels: Bug, critical

#731 Feature puma patches [9/x] element stretching
  example/geometry/t8_example_geometries.cxx
  src/t8_cmesh/t8_cmesh_readmshfile.cxx
  src/t8_cmesh/t8_cmesh_types.h
  src/t8_forest/t8_forest_cxx.cxx
  src/t8_forest/t8_forest_geometrical.h
  src/t8_forest/t8_forest_vtk.cxx
  src/t8_forest/t8_forest_vtk.h
  src/t8_geometry/t8_geometry.cxx
  src/t8_geometry/t8_geometry.h
  src/t8_geometry/t8_geometry_base.h
  src/t8_geometry/t8_geometry_base.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_analytic.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear_axis_aligned.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear_axis_aligned.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear_axis_aligned.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_zero.hxx
Labels: draft

#845 Delete element root len
  example/forest/t8_face_neighbor.cxx
  src/t8_element_c_interface.cxx
  src/t8_element_c_interface.h
  src/t8_element_cxx.hxx
  src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.cxx
  src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.hxx
  src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.cxx
  src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.hxx
  src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.cxx
  src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.hxx
  src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.cxx
  src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.hxx
  src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.cxx
  src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.hxx
  src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.cxx
  src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.hxx
  src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.cxx
  src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.hxx
  src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.cxx
  src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.hxx
Labels: enhancement, shouldn't take long, cleanup

#866 Fix curved vtk ref coords
  src/t8_forest/t8_forest_vtk.cxx
Labels: Bug, shouldn't take long

#872 Moved t8_forest_element_from_ref_coords implementation into cxx file.
  src/t8_forest/t8_forest_cxx.cxx
  src/t8_forest/t8_forest_geometrical.h
Labels: enhancement, shouldn't take long
