Repository DLR-AMR/t8code, pull requests merged in 2023-12, with the labels that each got.

#867 Bugfixes in curved geometry
  src/t8_cmesh/t8_cmesh_readmshfile.cxx
  src/t8_geometry/t8_geometry_helpers.c
  src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.cxx
Labels: Bug, shouldn't take long

#755 Add cmesh example triangulated spherical surface [1/n]
  example/cmesh/t8_cmesh_geometry_examples.cxx
  src/t8_cmesh/t8_cmesh_examples.c
  src/t8_cmesh/t8_cmesh_examples.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.hxx
  src/t8_geometry/t8_geometry_with_vertices.hxx
  src/t8_vec.h
Labels: enhancement, examples, Follow-up PR

#878 Updated citation and test files to new patch release v1.6.1.
  CITATION.cff
  test/t8_gtest_version.cxx
Labels: shouldn't take long, next release

#880 Fix Bug 873
  src/t8_cmesh/t8_cmesh_partition.c
  src/t8_geometry/t8_geometry.cxx
  src/t8_geometry/t8_geometry.h
Labels: Bug
