Repository DLR-AMR/t8code, pull requests merged in 2023-07, with the labels that each got.

#521 Feature puma patches [5/x] reimplement element centroid
  src/t8_element.c
  src/t8_element.h
  src/t8_forest/t8_forest_cxx.cxx
  src/t8_forest/t8_forest_geometrical.h
Labels: enhancement, shouldn't take long, draft

#602 Parametrize gtest eclass
  test/t8_gtest_eclass.cxx
Labels: shouldn't take long, tests, good first issue, cleanup

#614 Implemented wrapper for sc_shmem_prefix
  src/t8_data/t8_shmem.c
  src/t8_data/t8_shmem.h
  test/t8_data/t8_gtest_shmem.cxx
Labels: enhancement, shouldn't take long, tests

#553 Use new docker image for t8code tests
  .github/workflows/ci_playground.yml
  .github/workflows/tests_sc_p4est.yml
  .github/workflows/tests_t8code_linkage_parallel_debug.yml
  .github/workflows/tests_t8code_linkage_parallel_release.yml
  .github/workflows/tests_t8code_parallel.yml
  .github/workflows/tests_t8code_serial.yml
  src/t8_vtk/t8_vtk_reader.cxx
Labels: CI

#587 Set child_id to 0 for the root-element
  src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.c
Labels: Bug, shouldn't take long, good first issue

#607 Vtk parallel reader
  configure.ac
  example/IO/cmesh/vtk/t8_cmesh_read_from_vtk.cxx
  src/Makefile.am
  src/t8_vtk/t8_vtk_parallel.cxx
  src/t8_vtk/t8_vtk_parallel.hxx
  src/t8_vtk/t8_vtk_reader.cxx
  src/t8_vtk/t8_vtk_reader.hxx
  src/t8_vtk/t8_vtk_types.h
  src/t8_vtk/t8_vtk_unstructured.cxx
  test/t8_IO/t8_gtest_vtk_reader.cxx
  test/testfiles/test_parallel_file.pvtu
  test/testfiles/test_parallel_file_0.vtu
  test/testfiles/test_parallel_file_1.vtu
Labels: enhancement, New feature

#625 Automatically update GitHub Actions via Dependabot
  .github/dependabot.yml
Labels: enhancement, CI

#593 Ghosts via vtk api
  src/t8_forest/t8_forest.c
  src/t8_forest/t8_forest_to_vtkUnstructured.hxx
  src/t8_forest/t8_forest_vtk.cxx
  src/t8_forest/t8_forest_vtk.h
Labels: enhancement

#637 Feature remove obsolete indent guards
  src/t8_element_cxx.cxx
  src/t8_schemes/t8_default/t8_default_common/t8_default_common_cxx.cxx
Labels: shouldn't take long, good first issue, cleanup

#638 Only trigger the workflow on PR-events.
  .github/workflows/mattermost.yml
Labels: Bug, shouldn't take long

#639 Fix some typos
  src/t8_forest/t8_forest_general.h
  src/t8_forest/t8_forest_ghost.cxx
Labels: enhancement, shouldn't take long

#641 Let the indent script also run over benchmarking files
  scripts/find_all_source_files.scp
  scripts/indent_all_files.scp
Labels: shouldn't take long, cleanup

#635 Move t8_cmesh_set_tree_vertices
  example/geometry/t8_example_geometries.cxx
  src/Makefile.am
  src/t8_cmesh/t8_cmesh.c
  src/t8_cmesh/t8_cmesh_examples.c
  src/t8_cmesh/t8_cmesh_occ.cxx
  src/t8_cmesh/t8_cmesh_readmshfile.cxx
  src/t8_cmesh/t8_cmesh_triangle.c
  src/t8_cmesh_vtk_writer.h
  src/t8_geometry/t8_geometry_base.cxx
  src/t8_geometry/t8_geometry_base.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_analytic.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear_axis_aligned.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear_axis_aligned.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear_axis_aligned.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.hxx
  src/t8_geometry/t8_geometry_with_vertices.cxx
  src/t8_geometry/t8_geometry_with_vertices.h
  src/t8_geometry/t8_geometry_with_vertices.hxx
  src/t8_vtk/t8_vtk_reader.cxx
  test/t8_geometry/t8_gtest_geometry_occ.cxx
  test/t8_geometry/t8_gtest_point_inside.cxx
Labels: enhancement

#646 Fix orientation pad
  src/t8_cmesh/t8_cmesh_examples.c
Labels: examples, shouldn't take long

#647 Add check to only commit and push if there are changes
  .github/workflows/update_documentation.yml
Labels: shouldn't take long, CI

#649 Renable VTK output without linking to VTK library
  src/t8_forest/t8_forest.c
Labels: Bug

#608 Enable construction of cmesh from distributed vtkgrids.
  example/IO/cmesh/vtk/t8_cmesh_read_from_vtk.cxx
  src/t8_cmesh/t8_cmesh_commit.c
  src/t8_cmesh/t8_cmesh_vtk_writer.c
  src/t8_vtk/t8_vtk_parallel.cxx
  src/t8_vtk/t8_vtk_reader.cxx
  src/t8_vtk/t8_vtk_reader.hxx
  src/t8_vtk/t8_vtk_types.h
  test/t8_IO/t8_gtest_vtk_reader.cxx
Labels: New feature, tests

#626 Compute face connectivity for a cmesh by the tree vertices.
  benchmarks/Makefile.am
  benchmarks/t8_time_set_join_by_vertices.cxx
  configure.ac
  example/cmesh/Makefile.am
  example/cmesh/t8_cmesh_set_join_by_vertices.cxx
  src/Makefile.am
  src/t8.h
  src/t8_cmesh/t8_cmesh_helpers.c
  src/t8_cmesh/t8_cmesh_helpers.h
  test/Makefile.am
  test/t8_cmesh/t8_gtest_cmesh_set_join_by_vertices.cxx
  test/testfiles/test_cube_unstructured_1.inp
  test/testfiles/test_cube_unstructured_2.inp
Labels: New feature, tests

#651 Fix minor typo in pyramid scheme.
  example/cmesh/t8_cmesh_set_join_by_vertices.cxx
  src/t8_cmesh/t8_cmesh_helpers.h
  src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid.h
  src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.c
  test/t8_schemes/t8_gtest_pyra_connectivity.cxx
Labels: shouldn't take long, cleanup

#501 Fix issue 399 - Remove processing of linear geometries for speedup
  benchmarks/time_forest_partition.cxx
  src/t8_cmesh/t8_cmesh_readmshfile.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.hxx
Labels: enhancement

#652 Pretify Data-writing
  src/t8_forest/t8_forest_vtk.cxx
Labels: enhancement, shouldn't take long

#580 Test face descendant
  test/Makefile.am
  test/t8_schemes/t8_gtest_face_descendant.cxx
  test/t8_schemes/t8_gtest_pyra_face_descendant.cxx
Labels: tests

#654 Update README with a note on the Julia wrapper.
  README.md
Labels: documentation, Readme

#586 Add writing of child_indices for prism children at face
  src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.cxx
  src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.c
  src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.h
  test/t8_schemes/t8_gtest_face_descendant.cxx
Labels: enhancement
