Repository DLR-AMR/t8code, pull requests merged in 2023-04, with the labels that each got.

#504 Feature improve gtest output
  test/Makefile.am
Labels: tests

#509 Added BSD Statement
  doc/author_hergl.txt
Labels: shouldn't take long

#507 Fix Issue505 - README
  tutorials/README.md
Labels: shouldn't take long, documentation

#514 Feature puma patches [1/x] refactoring
  src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.cxx
  src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.hxx
  src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.cxx
  src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.hxx
  src/t8_schemes/t8_default/t8_default_line/t8_dline_bits.h
  src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.hxx
  src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.c
  src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.h
  src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.hxx
  src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.h
  src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.cxx
  src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.hxx
  src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.cxx
  src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.hxx
  src/t8_schemes/t8_default/t8_default_tet/t8_dtet_bits.h
  src/t8_schemes/t8_default/t8_default_tet/t8_dtri_to_dtet.h
  src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.cxx
  src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.hxx
  src/t8_schemes/t8_default/t8_default_tri/t8_dtri_bits.c
  src/t8_schemes/t8_default/t8_default_tri/t8_dtri_bits.h
  src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.cxx
  src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.hxx
  src/t8_schemes/t8_default/t8_default_vertex/t8_dvertex_bits.h
Labels: enhancement, documentation

#517 Improve tutorial documentation
  tutorials/general/t8_step0_helloworld.c
  tutorials/general/t8_step1_coarsemesh.c
  tutorials/general/t8_step2_uniform_forest.cxx
Labels: enhancement, shouldn't take long, documentation

#464 Adding a dummy-test for the cmesh_vtk_reader [vtk_to_cmesh 3/6]
  src/t8_cmesh_vtk_reader.hxx
  test/t8_IO/t8_gtest_vtk_reader.cxx
Labels: New feature, tests

#515 Feature puma patches [2/x] add element ref coords interface
  src/t8_element_cxx.hxx
  src/t8_schemes/t8_default/t8_default_common/t8_default_common_cxx.hxx
  src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.cxx
  src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.hxx
  src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.cxx
  src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.hxx
  src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.cxx
  src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.hxx
  src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.cxx
  src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.hxx
  src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.cxx
  src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.hxx
  src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.cxx
  src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.hxx
  src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.cxx
  src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.hxx
  src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.cxx
  src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.hxx
Labels: enhancement, shouldn't take long

#533 Fix linking problems in static mode.
  benchmarks/Makefile.am
  benchmarks/time_partition.cxx
  doc/author_kestener.txt
  example/IO/cmesh/netcdf/Makefile.am
  example/IO/cmesh/netcdf/t8_write_cmesh_netcdf.cxx
  example/IO/cmesh/tetgen/Makefile.am
  example/IO/cmesh/tetgen/t8_read_tetgen_file.cxx
  example/IO/cmesh/tetgen/t8_time_tetgen_file.cxx
  tutorials/Makefile.am
  tutorials/general/t8_step0_helloworld.cxx
  tutorials/general/t8_step1_coarsemesh.cxx
Labels: bug
