Repository DLR-AMR/t8code, pull requests merged in 2023-08, with the labels that each got.

#634 Parallel polydata reader
  configure.ac
  example/IO/cmesh/vtk/t8_cmesh_read_from_vtk.cxx
  scripts/t8indent_custom_datatypes.txt
  src/t8_vtk/t8_vtk_parallel.cxx
  src/t8_vtk/t8_vtk_parallel.hxx
  src/t8_vtk/t8_vtk_polydata.cxx
  src/t8_vtk/t8_vtk_polydata.hxx
  src/t8_vtk/t8_vtk_reader.cxx
  test/t8_IO/t8_gtest_vtk_reader.cxx
  test/testfiles/test_polydata.pvtp
  test/testfiles/test_polydata_0.vtp
  test/testfiles/test_polydata_1.vtp
Labels: enhancement, tests

#668 Indent vtk related files
  scripts/t8indent_custom_datatypes.txt
  src/t8_forest/t8_forest_to_vtkUnstructured.hxx
  src/t8_forest/t8_forest_vtk.cxx
  src/t8_vtk/t8_vtk_parallel.cxx
  src/t8_vtk/t8_vtk_parallel.hxx
  src/t8_vtk/t8_vtk_polydata.cxx
  src/t8_vtk/t8_vtk_polydata.hxx
  src/t8_vtk/t8_vtk_reader.cxx
  src/t8_vtk/t8_vtk_reader.hxx
  src/t8_vtk/t8_vtk_unstructured.cxx
  src/t8_vtk/t8_vtk_unstructured.hxx
  test/t8_IO/t8_gtest_vtk_reader.cxx
  test/t8_gtest_vtk_linkage.cxx
Labels: cleanup

#678 Add t8_element_destroy statements to improve memory management
  src/t8_forest/t8_forest.c
  src/t8_forest/t8_forest_cxx.cxx
  src/t8_forest/t8_forest_iterate.cxx
  src/t8_forest/t8_forest_partition.cxx
  src/t8_forest/t8_forest_private.h
  src/t8_schemes/t8_default/t8_default_common/t8_default_common_cxx.cxx
  test/t8_forest/t8_gtest_half_neighbors.cxx
  test/t8_schemes/t8_gtest_ancestor.cxx
  test/t8_schemes/t8_gtest_nca.cxx
Labels: enhancement

#679 Delete filter after usage
  src/t8_vtk/t8_vtk_reader.cxx
Labels: shouldn't take long

#681 Delete an INDENT-ON/OFF
  test/t8_gtest_eclass.cxx
Labels: shouldn't take long

#695 Update t8_cmesh_readmshfile
  src/t8_cmesh/t8_cmesh_readmshfile.cxx
Labels: shouldn't take long

#698 Update t8_cmesh_types
  src/t8_cmesh/t8_cmesh_types.h
Labels: shouldn't take long

#697 Update t8_cmesh_stash
  src/t8_cmesh/t8_cmesh_stash.c
  src/t8_cmesh/t8_cmesh_types.h
Labels: shouldn't take long

#696 Update t8_cmesh_refine
  src/t8_cmesh/t8_cmesh_refine.cxx
  src/t8_cmesh/t8_cmesh_save.c
  src/t8_cmesh/t8_cmesh_stash.c
  src/t8_cmesh/t8_cmesh_types.h
Labels: shouldn't take long

#693 Update t8_cmesh_helpers
  src/t8_cmesh/t8_cmesh_helpers.c
  src/t8_cmesh/t8_cmesh_occ.cxx
  src/t8_cmesh/t8_cmesh_readmshfile.cxx
  src/t8_cmesh/t8_cmesh_refine.cxx
  src/t8_cmesh/t8_cmesh_save.c
  src/t8_cmesh/t8_cmesh_stash.c
  src/t8_cmesh/t8_cmesh_types.h
Labels: shouldn't take long

#692 Update t8_cmesh_examples
  src/t8_cmesh/t8_cmesh_examples.c
  src/t8_cmesh/t8_cmesh_helpers.c
  src/t8_cmesh/t8_cmesh_occ.cxx
  src/t8_cmesh/t8_cmesh_readmshfile.cxx
  src/t8_cmesh/t8_cmesh_refine.cxx
  src/t8_cmesh/t8_cmesh_save.c
  src/t8_cmesh/t8_cmesh_stash.c
  src/t8_cmesh/t8_cmesh_types.h
Labels: shouldn't take long

#699 Add logo
  README.md
  t8code_logo.png
Labels: shouldn't take long, Readme

#701 indent test_t8_forest_incomplete files
  test/t8_forest_incomplete/t8_gtest_empty_global_tree.cxx
  test/t8_forest_incomplete/t8_gtest_empty_local_tree.cxx
  test/t8_forest_incomplete/t8_gtest_iterate_replace.cxx
  test/t8_forest_incomplete/t8_gtest_permute_hole.cxx
  test/t8_forest_incomplete/t8_gtest_recursive.cxx
Labels: shouldn't take long

#702 Update indentation test-t8_IO
  test/t8_IO/t8_gtest_vtk_reader.cxx
Labels: shouldn't take long

#703 Update indentation example-common
  example/common/t8_example_common.cxx
  example/common/t8_example_common.h
Labels: shouldn't take long

#691 Update prints to new column length.
  benchmarks/t8_time_prism_adapt.cxx
  benchmarks/time_forest_partition.cxx
Labels: shouldn't take long

#687 Update test/t8_forest/*
  test/t8_forest/t8_gtest_element_general_function.cxx
  test/t8_forest/t8_gtest_element_volume.cxx
  test/t8_forest/t8_gtest_find_owner.cxx
  test/t8_forest/t8_gtest_forest_commit.cxx
  test/t8_forest/t8_gtest_ghost_and_owner.cxx
  test/t8_forest/t8_gtest_ghost_exchange.cxx
  test/t8_forest/t8_gtest_half_neighbors.cxx
  test/t8_forest/t8_gtest_search.cxx
  test/t8_forest/t8_gtest_transform.cxx
Labels: shouldn't take long

#715 Update indentation schemes-default_vertex
  src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.cxx
Labels: shouldn't take long

#714 Update scheme-default_hex
  src/t8_schemes/t8_default/t8_default_hex/t8_default_hex.h
  src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.cxx
Labels: shouldn't take long

#711 Update test t8 data
  test/t8_data/t8_gtest_shmem.cxx
Labels: shouldn't take long, tests

#682 Remove indent on/off comments test schemes
  test/t8_schemes/t8_gtest_ancestor.cxx
  test/t8_schemes/t8_gtest_descendant.cxx
  test/t8_schemes/t8_gtest_element_count_leafs.cxx
  test/t8_schemes/t8_gtest_face_descendant.cxx
  test/t8_schemes/t8_gtest_find_parent.cxx
  test/t8_schemes/t8_gtest_init_linear_id.cxx
  test/t8_schemes/t8_gtest_nca.cxx
  test/t8_schemes/t8_gtest_pyra_face_neigh.cxx
  test/t8_schemes/t8_gtest_successor.cxx
Labels: shouldn't take long

#709 Update src directory files
  src/t8.h
  src/t8_cmesh.h
  src/t8_cmesh_readmshfile.h
  src/t8_eclass.c
  src/t8_element_c_interface.h
Labels: enhancement, shouldn't take long

#710 Update example forest
  example/forest/t8_test_face_iterate.cxx
  example/forest/t8_test_ghost.cxx
  example/forest/t8_test_ghost_large_level_diff.cxx
Labels: shouldn't take long

#722 Update indentation tutorial
  tutorials/features/t8_features_curved_meshes.cxx
  tutorials/general/t8_tutorial_build_cmesh.cxx
Labels: shouldn't take long

#723 Update indentation example_cmesh
  example/cmesh/t8_cmesh_create_partitioned.cxx
  example/cmesh/t8_cmesh_set_join_by_vertices.cxx
Labels: shouldn't take long

#724 Update indentation test_geometry
  test/t8_geometry/t8_gtest_geometry.cxx
  test/t8_geometry/t8_gtest_geometry_occ.cxx
  test/t8_geometry/t8_gtest_point_inside.cxx
Labels: shouldn't take long

#708 From GNU-indent to clang-format
  scripts/README.md
Labels: shouldn't take long, documentation

#677 Improve vtkGrid_to_vtkPointSet
  src/t8_vtk/t8_vtk_reader.cxx
Labels: enhancement, shouldn't take long

#727 Exclude logo from typo check
  .typos.toml
Labels: shouldn't take long
