Repository DLR-AMR/t8code, pull requests merged in 2023-05, with the labels that each got.

#540 Update README.md
  README.md
Labels: shouldn't take long, Readme

#518 Feature puma patches [3/x] add element ref coords implementation
  src/t8_schemes/t8_default/Makefile.am
  src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.cxx
  src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.hxx
  src/t8_schemes/t8_default/t8_default_hex/t8_dhex.h
  src/t8_schemes/t8_default/t8_default_hex/t8_dhex_bits.c
  src/t8_schemes/t8_default/t8_default_hex/t8_dhex_bits.h
  src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.cxx
  src/t8_schemes/t8_default/t8_default_line/t8_dline_bits.c
  src/t8_schemes/t8_default/t8_default_line/t8_dline_bits.h
  src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.cxx
  src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.c
  src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.h
  src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.cxx
  src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.c
  src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.h
  src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.cxx
  src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.hxx
  src/t8_schemes/t8_default/t8_default_quad/t8_dquad.h
  src/t8_schemes/t8_default/t8_default_quad/t8_dquad_bits.c
  src/t8_schemes/t8_default/t8_default_quad/t8_dquad_bits.h
  src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.cxx
  src/t8_schemes/t8_default/t8_default_tet/t8_dtet_bits.h
  src/t8_schemes/t8_default/t8_default_tet/t8_dtri_to_dtet.h
  src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.cxx
  src/t8_schemes/t8_default/t8_default_tri/t8_dtri_bits.c
  src/t8_schemes/t8_default/t8_default_tri/t8_dtri_bits.h
  src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.cxx
  src/t8_schemes/t8_default/t8_default_vertex/t8_dvertex_bits.c
  src/t8_schemes/t8_default/t8_default_vertex/t8_dvertex_bits.h
Labels: New feature

#519 Feature puma patches [4/x] adapt vtk output
  src/t8_forest/t8_forest_cxx.cxx
  src/t8_forest/t8_forest_geometrical.h
  src/t8_forest/t8_forest_vtk.cxx
Labels: enhancement, draft

#465 Add vtk_poly_data_reader [vtk_to_cmesh 4/6]
  config/t8_vtk.m4
  src/Makefile.am
  src/t8_cmesh/t8_cmesh_vtk_to_t8/t8_cmesh_vtk_polydata.cxx
  src/t8_cmesh/t8_cmesh_vtk_to_t8/t8_cmesh_vtk_polydata.hxx
Labels: New feature

#543 Add preprocessor macros for documentation
  doc/Doxyfile.in
Labels: enhancement, shouldn't take long, documentation

#544 Removed deprecated unit test file
  src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.cxx
  test/t8_forest/t8_test_user_data.cxx
  test/t8_geometry/t8_gtest_geometry_occ.cxx
  test/testfiles/test_msh_file_vers2_ascii.msh
Labels: shouldn't take long, cleanup

#551 Remove a t8_dtri_is_valid assertion, that gets called with a pyramid-descendant
  src/t8_schemes/t8_default/t8_default_tri/t8_dtri_bits.c
Labels: Bug, critical

#466 Cmesh vtk reader implementation [vtk_to_cmesh 5/6]
  config/t8_vtk.m4
  src/Makefile.am
  src/t8_cmesh/t8_cmesh_vtk_reader.cxx
  src/t8_cmesh/t8_cmesh_vtk_to_t8/t8_cmesh_vtk_polydata.cxx
  src/t8_cmesh/t8_cmesh_vtk_to_t8/t8_cmesh_vtk_polydata.hxx
  src/t8_cmesh/t8_cmesh_vtk_to_t8/t8_cmesh_vtk_unstructured.cxx
  src/t8_cmesh/t8_cmesh_vtk_to_t8/t8_cmesh_vtk_unstructured.hxx
  test/Makefile.am
  test/t8_IO/t8_gtest_vtk_reader.cxx
Labels: New feature, draft

#467 Cmesh vtk data set translator [vtk_to_cmesh 6/6]
  configure.ac
  example/IO/Makefile.am
  example/IO/cmesh/vtk/Makefile.am
  example/IO/cmesh/vtk/t8_cmesh_read_from_vtk.cxx
  src/Makefile.am
  src/t8_cmesh/t8_cmesh_vtk_reader.cxx
  src/t8_cmesh/t8_cmesh_vtk_to_t8/t8_cmesh_vtk_polydata.cxx
  src/t8_cmesh/t8_cmesh_vtk_to_t8/t8_cmesh_vtk_polydata.hxx
  src/t8_cmesh/t8_cmesh_vtk_to_t8/t8_cmesh_vtk_unstructured.cxx
  src/t8_cmesh/t8_cmesh_vtk_to_t8/t8_cmesh_vtk_unstructured.hxx
  src/t8_cmesh/t8_cmesh_vtk_to_t8/t8_vtk_types.h
  src/t8_cmesh_vtk_reader.hxx
  test/t8_IO/t8_gtest_vtk_reader.cxx
  test/testfiles/test_vtk_cube.vtp
  test/testfiles/test_vtk_tri.vtu
Labels: New feature

#508 Split vtk_writer function [1/2] - update vtk_writer
  src/t8_forest/t8_forest_vtk.cxx
  src/t8_forest/t8_forest_vtk.h
Labels: enhancement

#565 Added a newline in cmesh examples warnings output.
  src/t8_cmesh/t8_cmesh_examples.c
Labels: shouldn't take long, cleanup

#566 Fix pyramid element ref coords
  src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.c
Labels: Bug, shouldn't take long
