Repository DLR-AMR/t8code, pull requests merged in 2023-01, with the labels that each got.

#414 Tree indexing documentation
  src/t8_cmesh.h
  src/t8_cmesh/t8_cmesh_types.h
  src/t8_forest.h
  src/t8_forest/t8_forest_ghost.h
  src/t8_forest/t8_forest_types.h
Labels: shouldn't take long

#416 Removing testing line from PR template.
  pull_request_template.md
Labels: shouldn't take long, documentation

#410 Add a new geometry example using different geoms in the same mesh.
  example/geometry/t8_example_geometries.cxx
Labels: enhancement, examples, shouldn't take long

#420 Removed executable flag for two source code files in src/t8_cmesh.
  src/t8_cmesh/t8_cmesh_occ.cxx
  src/t8_cmesh/t8_cmesh_occ.hxx
Labels: shouldn't take long

#380 Fix issue 352
  src/t8_cmesh/t8_cmesh_readmshfile.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.h
Labels: bug
