Repository DLR-AMR/t8code, pull requests merged in 2023-09, with the labels that each got.

#734 remove custom datatypes from pr template
  pull_request_template.md
Labels: shouldn't take long, cleanup

#653 Cmesh example with curvilinear geometry: Squared Disk [1/n]
  example/cmesh/Makefile.am
  example/cmesh/t8_cmesh_geometry_examples.cxx
  src/Makefile.am
  src/t8_cmesh/t8_cmesh_examples.c
  src/t8_cmesh/t8_cmesh_examples.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.hxx
  src/t8_mat.h
Labels: New feature, examples, next release

#671 Fix issue #446
  src/t8_cmesh/t8_cmesh_examples.c
  src/t8_cmesh/t8_cmesh_readmshfile.cxx
  src/t8_eclass.c
  src/t8_eclass.h
  src/t8_geometry/t8_geometry_helpers.c
  src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.hxx
  test/t8_geometry/t8_gtest_geometry_occ.cxx
Labels: enhancement

#656 Use latex in doxygen documentation
  .github/workflows/add_release_documentation.yml
  .github/workflows/update_documentation.yml
  doc/Doxyfile.in
  example/geometry/t8_example_geometries.cxx
  src/t8_geometry/t8_geometry_base.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_analytic.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_analytic.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear_axis_aligned.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear_axis_aligned.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_zero.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_zero.hxx
  src/t8_schemes/t8_default/t8_default_hex/t8_dhex_bits.h
  src/t8_schemes/t8_default/t8_default_line/t8_dline_bits.h
  src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.h
  src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.h
  src/t8_schemes/t8_default/t8_default_quad/t8_dquad_bits.h
  src/t8_schemes/t8_default/t8_default_tet/t8_dtet_bits.h
  src/t8_schemes/t8_default/t8_default_tri/t8_dtri_bits.h
Labels: enhancement, documentation

#661 Feature puma patches [7/x] Batch processing of element ref_coords
  src/t8_element_cxx.hxx
  src/t8_forest/t8_forest_cxx.cxx
  src/t8_schemes/t8_default/t8_default_common/t8_default_common_cxx.hxx
  src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.cxx
  src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.hxx
  src/t8_schemes/t8_default/t8_default_hex/t8_dhex_bits.c
  src/t8_schemes/t8_default/t8_default_hex/t8_dhex_bits.h
  src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.cxx
  src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.hxx
  src/t8_schemes/t8_default/t8_default_line/t8_dline_bits.c
  src/t8_schemes/t8_default/t8_default_line/t8_dline_bits.h
  src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.cxx
  src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.hxx
  src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.c
  src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.h
  src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.cxx
  src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.hxx
  src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.c
  src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.h
  src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.cxx
  src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.hxx
  src/t8_schemes/t8_default/t8_default_quad/t8_dquad_bits.c
  src/t8_schemes/t8_default/t8_default_quad/t8_dquad_bits.h
  src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.cxx
  src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.hxx
  src/t8_schemes/t8_default/t8_default_tet/t8_dtet_bits.h
  src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.cxx
  src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.hxx
  src/t8_schemes/t8_default/t8_default_tri/t8_dtri_bits.c
  src/t8_schemes/t8_default/t8_default_tri/t8_dtri_bits.h
  src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.cxx
  src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.hxx
  src/t8_schemes/t8_default/t8_default_vertex/t8_dvertex_bits.c
  src/t8_schemes/t8_default/t8_default_vertex/t8_dvertex_bits.h
Labels: enhancement, Follow-up PR

#662 Feature puma patches [8/x] Batch processing of tree ref_coords [1/x] Interface
  example/geometry/t8_example_geometries.cxx
  src/t8_forest/t8_forest_cxx.cxx
  src/t8_forest/t8_forest_geometrical.h
  src/t8_forest/t8_forest_vtk.cxx
  src/t8_geometry/t8_geometry.cxx
  src/t8_geometry/t8_geometry.h
  src/t8_geometry/t8_geometry_base.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_analytic.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_analytic.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear_axis_aligned.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear_axis_aligned.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_zero.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_zero.hxx
  test/t8_geometry/t8_gtest_geometry.cxx
  test/t8_geometry/t8_gtest_geometry_occ.cxx
Labels: enhancement, Follow-up PR

#746 Improve forest vtk writer api
  src/t8_forest/t8_forest_vtk.cxx
Labels: enhancement, shouldn't take long

#745 Remove some indent markers
  scripts/README.md
  src/t8_eclass.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear_axis_aligned.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.cxx
  src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.c
  src/t8_vtk/t8_vtk_parallel.hxx
  src/t8_vtk/t8_vtk_reader.hxx
  test/t8_geometry/t8_gtest_point_inside.cxx
  test/t8_gtest_occ_linkage.cxx
Labels: shouldn't take long, cleanup

#664 Feature puma patches [8/x] Batch processing of tree ref_coords [2/x] Linear geometries
  example/geometry/t8_example_geometries.cxx
  src/t8_geometry/t8_geometry_helpers.c
  src/t8_geometry/t8_geometry_helpers.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear_axis_aligned.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.cxx
Labels: enhancement, Follow-up PR

#765 Update clang-format to v17.0.1.
  .github/workflows/check_indentation.yml
  example/geometry/t8_example_geometries.cxx
  scripts/check_if_file_indented.scp
  scripts/t8indent
Labels: shouldn't take long, CI

#770 Bug fix: eclass_compare
  src/t8_eclass.c
Labels: Bug

#753 Convert squared disk cmesh example to batched version.
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.hxx
Labels: enhancement, examples

#771 Check the inequalities definied for eclasses
  test/t8_gtest_eclass.cxx
Labels: shouldn't take long, tests
