Repository DLR-AMR/t8code, pull requests merged in 2023-10, with the labels that each got.

#779 Fixed spell errors raised by `typos-cli 1.16.17`.
  benchmarks/time_partition.cxx
  src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.cxx
Labels: shouldn't take long, cleanup

#799 Added a test for the face-orientation
  test/t8_gtest_eclass.cxx
Labels: shouldn't take long, tests

#803 Test for element ref coords
  src/t8_cmesh/t8_cmesh_examples.c
  src/t8_element.c
  src/t8_element.h
  src/t8_forest/t8_forest_cxx.cxx
  src/t8_geometry/t8_geometry.cxx
  src/t8_schemes/t8_default/t8_default_line/t8_dline_bits.c
  src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.c
  src/t8_schemes/t8_default/t8_default_tri/t8_dtri_bits.c
  test/Makefile.am
  test/t8_schemes/t8_gtest_element_ref_coords.cxx
Labels: Bug, tests, draft
