Repository DLR-AMR/t8code, pull requests merged in 2024-03, with the labels that each got.

#939 Add parametrized cmesh example
  src/t8_cmesh/t8_cmesh_examples.c
  test/t8_cmesh_generator/t8_cmesh_example_sets.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_disjoint_bricks_param.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_params.hxx
Labels: enhancement, shouldn't take long, tests

#965 Added empty cmeshes
  test/t8_cmesh_generator/t8_cmesh_example_sets.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_empty.hxx
Labels: enhancement, shouldn't take long, tests, Follow-up PR

#973 Disable tests instead of skipping them
  scripts/find_disabled_tests.scp
  test/t8_cmesh/t8_gtest_cmesh_copy.cxx
  test/t8_forest/t8_gtest_ghost_delete.cxx
  test/t8_forest_incomplete/t8_gtest_empty_global_tree.cxx
Labels: enhancement, shouldn't take long, tests

#897 Moving the negative volume check into the geometry module
  src/Makefile.am
  src/t8_cmesh.h
  src/t8_cmesh/t8_cmesh.c
  src/t8_cmesh/t8_cmesh_examples.c
  src/t8_geometry/t8_geometry.cxx
  src/t8_geometry/t8_geometry.h
  src/t8_geometry/t8_geometry_base.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear_axis_aligned.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear_axis_aligned.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_zero.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_zero.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_zero.hxx
  src/t8_geometry/t8_geometry_with_vertices.cxx
  src/t8_geometry/t8_geometry_with_vertices.hxx
  test/t8_cmesh/t8_gtest_cmesh_face_is_boundary.cxx
  test/t8_cmesh/t8_gtest_cmesh_set_partition_offsets.cxx
  tutorials/general/t8_tutorial_search.cxx
Labels: enhancement

#964 Gtest print eclass
  test/t8_cmesh/t8_gtest_bcast.cxx
  test/t8_cmesh/t8_gtest_cmesh_face_is_boundary.cxx
  test/t8_forest/t8_gtest_find_owner.cxx
  test/t8_forest_incomplete/t8_gtest_empty_local_tree.cxx
  test/t8_forest_incomplete/t8_gtest_permute_hole.cxx
  test/t8_forest_incomplete/t8_gtest_recursive.cxx
  test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_cad.cxx
  test/t8_geometry/t8_gtest_geometry.cxx
  test/t8_gtest_eclass.cxx
  test/t8_gtest_macros.hxx
  test/t8_schemes/t8_gtest_ancestor.cxx
  test/t8_schemes/t8_gtest_boundary_extrude.cxx
  test/t8_schemes/t8_gtest_child_parent_face.cxx
  test/t8_schemes/t8_gtest_default.cxx
  test/t8_schemes/t8_gtest_descendant.cxx
  test/t8_schemes/t8_gtest_element_count_leaves.cxx
  test/t8_schemes/t8_gtest_equal.cxx
  test/t8_schemes/t8_gtest_face_descendant.cxx
  test/t8_schemes/t8_gtest_face_neigh.cxx
  test/t8_schemes/t8_gtest_find_parent.cxx
  test/t8_schemes/t8_gtest_init_linear_id.cxx
  test/t8_schemes/t8_gtest_nca.cxx
  test/t8_schemes/t8_gtest_root.cxx
  test/t8_schemes/t8_gtest_successor.cxx
Labels: enhancement, tests

#966 Add new_periodic examples
  test/t8_cmesh_generator/t8_cmesh_example_sets.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_periodic.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_params.hxx
Labels: enhancement, shouldn't take long, tests, Follow-up PR

#976 Added missing header files for installation
  src/Makefile.am
Labels: Bug, shouldn't take long, fix

#977 update number of the corner of the second vertex
  example/cmesh/t8_cmesh_hypercube_pad.cxx
  src/t8_geometry/t8_geometry_helpers.c
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear_axis_aligned.cxx
  test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_linear.cxx
  test/t8_geometry/t8_gtest_geometry_macros.hxx
  test/t8_geometry/t8_gtest_point_inside.cxx
Labels: Bug, shouldn't take long

#979 Cleanup element interface
  .gitignore
  src/t8_data/t8_containers.cxx
  src/t8_element_c_interface.cxx
  src/t8_element_c_interface.h
  src/t8_element_cxx.cxx
  src/t8_element_cxx.hxx
  src/t8_forest/t8_forest_cxx.cxx
  src/t8_schemes/t8_default/t8_default_common/t8_default_common_cxx.cxx
  src/t8_schemes/t8_default/t8_default_common/t8_default_common_cxx.hxx
  src/t8_schemes/t8_default/t8_default_cxx.cxx
  src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.cxx
  src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.hxx
  src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.cxx
  src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.hxx
  src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.cxx
  src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.hxx
  src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.cxx
  src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.hxx
  src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.c
  src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.cxx
  src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.hxx
  src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.cxx
  src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.hxx
  src/t8_schemes/t8_default/t8_default_tet/t8_dtet.h
  src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.cxx
  src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.hxx
  src/t8_schemes/t8_default/t8_default_tri/t8_dtri_bits.c
  src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.cxx
  src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.hxx
  test/CMakeLists.txt
  test/Makefile.am
  test/t8_forest/t8_gtest_element_general_function.cxx
  test/t8_schemes/t8_gtest_successor.cxx
Labels: next release

#967 Activate new parametrized cmesh tests in current testsuit
  src/CMakeLists.txt
  src/Makefile.am
  src/t8_cmesh/t8_cmesh_testcases.c
  src/t8_cmesh/t8_cmesh_testcases.h
  test/t8_cmesh/t8_gtest_cmesh_copy.cxx
  test/t8_cmesh/t8_gtest_cmesh_partition.cxx
  test/t8_cmesh/t8_gtest_cmesh_set_join_by_vertices.cxx
  test/t8_cmesh/t8_gtest_cmesh_set_partition_offsets.cxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_hypercube_param.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_params.hxx
  test/t8_forest/t8_gtest_forest_commit.cxx
  test/t8_forest/t8_gtest_ghost_and_owner.cxx
  test/t8_forest/t8_gtest_ghost_exchange.cxx
  test/t8_forest_incomplete/t8_gtest_iterate_replace.cxx
  test/t8_gtest_macros.hxx
  tutorials/general/t8_step7_interpolation.cxx
Labels: enhancement, tests

#986 Fix geometry example
  example/geometry/t8_example_geometries.cxx
  src/t8_geometry/t8_geometry_base.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_analytic.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_analytic.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_analytic.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_cad.cxx
Labels: examples, fix

#851 Geometry based on mapping by Lagrange basis functions
  doc/author_csati.txt
  src/Makefile.am
  src/t8_cmesh/t8_cmesh_types.h
  src/t8_geometry/t8_geometry.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_lagrange.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_lagrange.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_lagrange.hxx
  test/Makefile.am
  test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_linear.cxx
  test/t8_geometry/t8_gtest_geometry_lagrange.cxx
  test/t8_geometry/t8_gtest_geometry_macros.hxx
Labels: New feature

#991 Move t8_mat to installed headers
  src/Makefile.am
  src/t8_mat.h
Labels: fix

#995 Introduce Makro to controll the number of points used for testing
  test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_lagrange.cxx
  test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_linear.cxx
  test/t8_gtest_macros.hxx
Labels: enhancement, shouldn't take long, tests

#742 Feature curved tetrahedron
  configure.ac
  src/t8_cmesh/t8_cmesh_readmshfile.cxx
  src/t8_eclass.c
  src/t8_eclass.h
  src/t8_geometry/t8_geometry_helpers.c
  src/t8_geometry/t8_geometry_helpers.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_cad.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_cad.hxx
  tutorials/Makefile.am
  tutorials/features/t8_features_curved_meshes_generate_cmesh_hex.geo
  tutorials/features/t8_features_curved_meshes_generate_cmesh_quad.geo
  tutorials/features/t8_features_curved_meshes_generate_cmesh_tet.geo
  tutorials/features/t8_features_curved_meshes_generate_cmesh_tri.geo
Labels: New feature, examples, next release

#942 Test - Additional geometry tests
  src/t8_schemes/t8_default/t8_default_hex/t8_dhex.h
  test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_cad.cxx
Labels: tests, next release

#996 Remove debugging output from Lagrange test
  test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_lagrange.cxx
Labels: enhancement, shouldn't take long

#989 Add handler to installed headers
  src/Makefile.am
Labels: fix

#1001 Rename occ test
  test/CMakeLists.txt
  test/Makefile.am
  test/t8_gtest_occ_linkage.cxx
Labels: shouldn't take long, tests

#1004 Fix a typo in a comment
  src/t8_cmesh.h
Labels: shouldn't take long, documentation

#972 Feature 923 cmesh add attr error
  src/t8_cmesh/t8_cmesh.cxx
  test/Makefile.am
  test/t8_cmesh/t8_gtest_cmesh_add_attributes_when_derive.cxx
Labels: enhancement, tests, next release
