Repository DLR-AMR/t8code, pull requests merged in 2024-12, with the labels that each got.

#1319 Fix: Add missing headers in order to import definitions.
  src/t8_geometry/t8_geometry_implementations/t8_geometry_analytic.h
  src/t8_geometry/t8_geometry_with_vertices.h
Labels: shouldn't take long, fix, priority: low, workload: low

#1321 Add ctest Testing folder to .gitignore
  .gitignore
Labels: shouldn't take long

#1322 Add tag labels to pr template
  pull_request_template.md
Labels: tag: patch

#1324 Increase ci timeout limit
  .github/workflows/tests_cmake_t8code.yml
  .github/workflows/tests_cmake_t8code_api.yml
  .github/workflows/tests_cmake_t8code_linkage.yml
  .github/workflows/tests_cmake_t8code_w_shipped_submodules.yml
Labels: CI, critical

#1326 Configure with -O1 on debug-builds
  .github/workflows/build_cmake_tarball.yml
  .github/workflows/tests_cmake_t8code.yml
  .github/workflows/tests_cmake_t8code_api.yml
  .github/workflows/tests_cmake_t8code_linkage.yml
  .github/workflows/tests_cmake_t8code_w_shipped_submodules.yml
  .github/workflows/tests_cmake_testsuite.yml
  test/t8_schemes/t8_gtest_root.cxx
Labels: enhancement, shouldn't take long, CI, priority: high
