Repository DLR-AMR/t8code, pull requests merged in 2024-11, with the labels that each got.

#1288 Remove autotools CI
  .github/workflows/test_tarball.yml
  .github/workflows/tests_sc_p4est.yml
  .github/workflows/tests_t8code_linkage_parallel_debug.yml
  .github/workflows/tests_t8code_linkage_parallel_release.yml
  .github/workflows/tests_t8code_parallel.yml
  .github/workflows/tests_t8code_serial.yml
Labels: shouldn't take long, CI, priority: low, workload: low

#1291 Fix spelling-errors
  example/version/t8_version.cxx
  src/t8_cmesh/t8_cmesh_readmshfile.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.cxx
Labels: shouldn't take long, good first issue, Typos, priority: high, workload: low

#1003 Feature ghost tuning
  src/t8_forest/t8_forest.cxx
  src/t8_forest/t8_forest_ghost.cxx
Labels: enhancement, priority: low

#1298 Upgrade to C++ 20
  CMakeLists.txt
Labels: C++, priority: medium, workload: low, CMake

#1296 Fix: More robust connect cmesh faces by vertices and sphere cmesh examples
  src/t8_cmesh/t8_cmesh_examples.cxx
  src/t8_cmesh/t8_cmesh_helpers.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.cxx
Labels: enhancement, shouldn't take long, fix, priority: medium, workload: low

#1281 Remove Fortran from language dependencies when not needed.
  CMakeLists.txt
Labels: shouldn't take long, fix, priority: medium, workload: low, Fortran, CMake

#1308 Correct mail address
  doc/author_fussbroich.txt
Labels: shouldn't take long

#1266 Feature netcdf geospatial data build mesh
  doc/author_radmer.txt
  example/IO/netcdf_input/t8_build_mesh_from_nc_file.cxx
  src/Makefile.am
  src/t8_cmesh/t8_cmesh_examples.cxx
  src/t8_netcdf/t8_nc_mesh.cxx
  src/t8_netcdf/t8_nc_mesh.hxx
  test/CMakeLists.txt
  test/Makefile.am
  test/t8_forest/t8_gtest_build_forest_from_geo_domain.cxx
Labels: New feature

#1310 Update functionname to naming scheme
  src/t8_data/t8_element_array_iterator.hxx
  src/t8_forest/t8_forest.cxx
Labels: cleanup, priority: low, workload: low
