Repository DLR-AMR/t8code, pull requests merged in 2024-07, with the labels that each got.

#1094 Fix calculation of attribute_data_offset
  src/t8_cmesh/t8_cmesh_commit.cxx
  src/t8_cmesh/t8_cmesh_trees.c
Labels: draft

#1066 CMake: Adding option to compile with OpenCASCADE
  CMakeLists.txt
  src/CMakeLists.txt
Labels: shouldn't take long, good first issue

#1009 Test geometry cad prisms
  test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_cad.cxx
Labels: enhancement, New feature, tests, Follow-up PR

#1116 fix a typo in a warning message
  src/t8_data/t8_shmem.c
Labels: shouldn't take long, fix

#1110 Cmake: set project version and libt8 shared library soname and version
  CMakeLists.txt
  cmake/GitProjectVersion.cmake
  src/CMakeLists.txt
Labels: enhancement

#1117 fix some typos
  src/t8_schemes/t8_default/t8_default.hxx
  src/t8_schemes/t8_default/t8_default_c_interface.h
Labels: shouldn't take long, fix, Typos

#1122 Fix: building examples with the CMake build system
  example/CMakeLists.txt
Labels: shouldn't take long, fix

#1124 More const in t8_cmesh
  src/t8_cmesh.h
  src/t8_cmesh/t8_cmesh.cxx
  src/t8_cmesh/t8_cmesh_trees.c
Labels: enhancement, shouldn't take long

#1119 Cmake: add RelWithDebInfo build type and fixed binary embedded build info
  CMakeLists.txt
  src/CMakeLists.txt
Labels: enhancement, next release, fix

#1127 More const for t8_cmesh_partition
  src/t8_cmesh/t8_cmesh_copy.c
  src/t8_cmesh/t8_cmesh_geometry.cxx
  src/t8_cmesh/t8_cmesh_netcdf.c
  src/t8_cmesh/t8_cmesh_offset.c
  src/t8_cmesh/t8_cmesh_partition.cxx
Labels: shouldn't take long

#1126 Fix a small TODO
  src/t8_cmesh/t8_cmesh_partition.cxx
Labels: enhancement, shouldn't take long, good first issue

#1128 More const in t8_cmesh_readmshfile
  src/t8_cmesh/t8_cmesh_partition.cxx
  src/t8_cmesh/t8_cmesh_readmshfile.cxx
Labels: shouldn't take long

#1115 Simplified C interface for registering geometries in cmeshes.
  src/t8_cmesh.h
  src/t8_cmesh/t8_cmesh.cxx
  src/t8_cmesh/t8_cmesh_examples.cxx
  src/t8_cmesh/t8_cmesh_geometry.cxx
  src/t8_geometry/t8_geometry_handler.cxx
  src/t8_geometry/t8_geometry_handler.hxx
Labels: shouldn't take long, next release, cleanup

#1140 Add CMake option to enable less tests.
  CMakeLists.txt
  src/CMakeLists.txt
Labels: shouldn't take long, tests, next release

#1102 Improve edgecase handling for empty trees
  src/t8_data/t8_containers.cxx
  src/t8_forest/t8_forest.cxx
  src/t8_forest/t8_forest_partition.cxx
Labels: next release

#1138 Fixed failing version test with CMake.
  cmake/GitProjectVersion.cmake
  src/CMakeLists.txt
  src/t8_version.c
Labels: shouldn't take long, tests, next release, fix

#1146 Cmake: rename inconsistent CMake build option
  CMakeLists.txt
  doc/CMakeLists.txt
Labels: shouldn't take long, cleanup

#1151 Fixed memory leak in tutorial step 06 and added documentation.
  src/t8_forest/t8_forest_general.h
  tutorials/general/t8_step6_stencil.cxx
Labels: Bug, examples, shouldn't take long, next release, priority: low, workload: low

#1153 Fixed t8code init build config flags reporting
  src/CMakeLists.txt
  src/t8.c
Labels: shouldn't take long, cleanup, priority: low, workload: low

#1141 CMake: added netCDF option
  CMakeLists.txt
  src/CMakeLists.txt
Labels: enhancement, shouldn't take long

#1139 Feature enable more procs for check
  Makefile.am
  config/t8_mpi.m4
  configure.ac
Labels: enhancement, shouldn't take long, tests

#1154 Adding CMake pedantic build mode option.
  CMakeLists.txt
  src/CMakeLists.txt
Labels: shouldn't take long, next release, workload: low

#1136 Fix a not intended assertion in t8_forest_partition_fill_buffer_data
  src/t8_forest/t8_forest_partition.cxx
  src/t8_forest/t8_forest_partition.h
  test/CMakeLists.txt
  test/Makefile.am
  test/t8_forest/t8_gtest_partition_data.cxx
Labels: tests, fix

#1166 Fix internal header include
  benchmarks/t8_time_fractal.cxx
  src/CMakeLists.txt
  test/t8_forest/t8_gtest_element_is_leaf.cxx
  test/t8_forest/t8_gtest_ghost_delete.cxx
  test/t8_forest/t8_gtest_transform.cxx
  tutorials/general/t8_step7_interpolation.cxx
Labels: shouldn't take long, cleanup, workload: low

#1165 Cleanup benchmark time_new_refine
  benchmarks/CMakeLists.txt
  benchmarks/Makefile.am
  benchmarks/time_new_refine.c
Labels: cleanup

#1145 Transform vtk-writer interface into a class
  src/t8_vtk/t8_vtk_writer.hxx
  src/t8_vtk/t8_vtk_writer_impl.hxx
Labels: enhancement, Follow-up PR, C++

#1144 Enhance vtk writer for cmesh and forests
  src/Makefile.am
  src/t8_cmesh/t8_cmesh_vtk_writer.c
  src/t8_forest/t8_forest_vtk.h
  src/t8_vtk/t8_vtk_writer.hxx
  src/t8_vtk/t8_vtk_writer_helper.hxx
  test/CMakeLists.txt
  test/Makefile.am
  test/t8_IO/t8_gtest_vtk_writer.cxx
  tutorials/general/t8_step1_coarsemesh.cxx
  tutorials/general/t8_step2_uniform_forest.cxx
Labels: enhancement, C++, priority: medium, workload: medium

#1172 Update contributing guidelines
  CONTRIBUTING.md
Labels: Wiki, documentation, priority: high, workload: low

#1178 CMake: remove modification to user-defined CMAKE_{C,CXX}_FLAGS
  CMakeLists.txt
Labels: shouldn't take long, cleanup, priority: medium, workload: low

#1179 Added CMake installation instructions in the INSTALL file
  INSTALL
Labels: shouldn't take long, documentation, next release, priority: medium, workload: low

#1120 Addition: Example executable to quickly convert a Gmsh file into a VTU file for visualization in Paraview
  example/CMakeLists.txt
  example/IO/Makefile.am
  example/IO/forest/gmsh/Makefile.am
  example/IO/forest/gmsh/t8_gmsh_to_vtk.cxx
  src/t8_cmesh/t8_cmesh_readmshfile.cxx
Labels: enhancement, examples, shouldn't take long, next release

#1149 Fortran c file
  Makefile.am
  api/Makefile.am
  api/t8_fortran_interface/t8_fortran_interface.c
  api/t8_fortran_interface/t8_fortran_interface.h
Labels: good first issue, Follow-up PR, priority: high
