Repository DLR-AMR/t8code, pull requests merged in 2024-02, with the labels that each got.

#917 changed all 'leafs' to 'leaves' after spellchecker update
  .gitignore
  example/forest/t8_test_face_iterate.cxx
  src/t8_cmesh/t8_cmesh_cxx.cxx
  src/t8_element_c_interface.cxx
  src/t8_element_c_interface.h
  src/t8_element_cxx.hxx
  src/t8_forest/t8_forest.c
  src/t8_forest/t8_forest_cxx.cxx
  src/t8_forest/t8_forest_general.h
  src/t8_forest/t8_forest_ghost.cxx
  src/t8_forest/t8_forest_iterate.cxx
  src/t8_forest/t8_forest_iterate.h
  src/t8_forest/t8_forest_private.h
  src/t8_schemes/t8_default/t8_default_common/t8_default_common_cxx.cxx
  src/t8_schemes/t8_default/t8_default_common/t8_default_common_cxx.hxx
  src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.hxx
  src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.hxx
  src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.hxx
  src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.hxx
  src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.hxx
  src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.hxx
  src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.hxx
  src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.hxx
  test/Makefile.am
  test/t8_forest/t8_gtest_search.cxx
  test/t8_schemes/t8_gtest_ancestor.cxx
  test/t8_schemes/t8_gtest_element_count_leaves.cxx
  test/t8_schemes/t8_gtest_init_linear_id.cxx
  test/t8_schemes/t8_gtest_nca.cxx
  tutorials/general/t8_tutorial_search.cxx
Labels: enhancement, next release

#918 add testcase include and change include order in gtest_macros
  test/t8_gtest_macros.hxx
Labels: shouldn't take long, next release, fix

#921 Feature test cmesh copy
  test/Makefile.am
  test/t8_cmesh/t8_gtest_cmesh_copy.cxx
Labels: next release

#916 Test geometry occ linear
  src/t8_cmesh/t8_cmesh.c
  src/t8_geometry/t8_geometry_with_vertices.h
  test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_occ.cxx
  test/t8_gtest_macros.hxx
Labels: next release

#913 Let t8ddy update latest dev redirection
  .github/workflows/add_release_documentation.yml
Labels: CI, next release

#928 Remove binary vtk option
  src/t8_cmesh/t8_cmesh_vtk_writer.c
  src/t8_forest/t8_forest_vtk.cxx
  src/t8_vtk.h
Labels: next release

#792 Add cmesh examples triangulated spherical shell (octahedron & icosahedron versions) [5/n].
  example/cmesh/t8_cmesh_geometry_examples.cxx
  src/t8_cmesh/t8_cmesh_examples.c
  src/t8_cmesh/t8_cmesh_examples.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.hxx
  src/t8_vec.h
Labels: New feature, examples

#933 Fix typo, and delete documentation in .c-file (duplicate)
  src/t8_cmesh.h
  src/t8_cmesh/t8_cmesh.c
Labels: enhancement, shouldn't take long

#871 Enhance cmesh testing
  test/Makefile.am
  test/t8_cmesh/t8_gtest_cmesh_copy.cxx
  test/t8_cmesh_generator/t8_cmesh_example_sets.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_bigmesh_param.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_from_class_param.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_prism_cake_param.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_params.hxx
  test/t8_cmesh_generator/t8_gtest_cmesh_cartestian_product.hxx
  test/t8_cmesh_generator/t8_gtest_cmesh_generator_test.cxx
  test/t8_cmesh_generator/t8_gtest_cmesh_sum_of_sets.hxx
Labels: enhancement, New feature, tests, discussion, draft

#927 Remove scale parameter from cmesh vtk
  benchmarks/time_forest_partition.cxx
  benchmarks/time_partition.cxx
  example/IO/cmesh/gmsh/t8_load_and_refine_square_w_hole.cxx
  example/IO/cmesh/gmsh/t8_read_msh_file.cxx
  example/IO/cmesh/t8_cmesh_load_save.cxx
  example/IO/cmesh/tetgen/t8_forest_from_tetgen.cxx
  example/IO/cmesh/tetgen/t8_read_tetgen_file.cxx
  example/IO/cmesh/tetgen/t8_time_tetgen_file.cxx
  example/IO/cmesh/triangle/t8_read_triangle_file.cxx
  example/IO/cmesh/vtk/t8_cmesh_read_from_vtk.cxx
  example/advect/t8_advection.cxx
  example/cmesh/t8_cmesh_geometry_examples.cxx
  example/cmesh/t8_cmesh_hypercube_pad.cxx
  example/cmesh/t8_cmesh_partition.cxx
  example/forest/t8_test_face_iterate.cxx
  example/forest/t8_test_ghost.cxx
  example/forest/t8_test_ghost_large_level_diff.cxx
  src/t8_cmesh/t8_cmesh_vtk_writer.c
  src/t8_cmesh_vtk_writer.h
  tutorials/general/t8_step1_coarsemesh.cxx
  tutorials/general/t8_tutorial_build_cmesh.cxx
Labels: enhancement, next release

#937 Removed missing scale parameter deletions.
  example/cmesh/t8_cmesh_geometry_examples.cxx
Labels: Bug, shouldn't take long

#938 Add new constructor for similar cmeshes
  test/t8_cmesh_generator/t8_cmesh_example_sets.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_comm.hxx
  test/t8_cmesh_generator/t8_gtest_cmesh_cartestian_product.hxx
Labels: enhancement, shouldn't take long, tests

#751 Feature point inside check for axis aligned geom
  src/t8_cmesh/t8_cmesh.c
  src/t8_cmesh/t8_cmesh_examples.c
  src/t8_forest/t8_forest_cxx.cxx
  src/t8_forest/t8_forest_general.h
  src/t8_geometry/t8_geometry.cxx
  src/t8_geometry/t8_geometry_base.hxx
  src/t8_geometry/t8_geometry_helpers.c
  src/t8_geometry/t8_geometry_helpers.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_analytic.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear_axis_aligned.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear_axis_aligned.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_zero.hxx
  src/t8_geometry/t8_geometry_with_vertices.hxx
  test/Makefile.am
  test/t8_geometry/t8_gtest_point_inside.cxx
  tutorials/general/t8_tutorial_search.cxx
Labels: enhancement, tests, Follow-up PR

#943 Update EXPECT_VEC3_EQ
  src/t8_vec.h
  test/t8_gtest_vec.cxx
Labels: shouldn't take long, tests

#941 Add new test
  test/t8_cmesh_generator/t8_cmesh_example_sets.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_hypercube_param.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_params.hxx
Labels: enhancement, shouldn't take long, tests

#944 CAD instead of OCC
  .github/workflows/tests_t8code_linkage_parallel_debug.yml
  .github/workflows/tests_t8code_linkage_parallel_release.yml
  benchmarks/t8_time_set_join_by_vertices.cxx
  benchmarks/time_forest_partition.cxx
  example/advect/t8_advection.cxx
  example/cmesh/t8_cmesh_set_join_by_vertices.cxx
  example/geometry/t8_example_geometries.cxx
  src/Makefile.am
  src/t8_cmesh/t8_cmesh_cad.cxx
  src/t8_cmesh/t8_cmesh_cad.hxx
  src/t8_cmesh/t8_cmesh_readmshfile.cxx
  src/t8_cmesh/t8_cmesh_types.h
  src/t8_cmesh_readmshfile.h
  src/t8_geometry/t8_geometry.h
  src/t8_geometry/t8_geometry_helpers.c
  src/t8_geometry/t8_geometry_implementations/t8_geometry_cad.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_cad.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_cad.hxx
  test/Makefile.am
  test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_cad.cxx
  test/t8_gtest_cad_linkage.cxx
  tutorials/features/t8_features_curved_meshes.cxx
Labels: discussion, next release, draft

#951 Skip vtk reader test for MPI sizes other than 2.
  test/t8_IO/t8_gtest_vtk_reader.cxx
Labels: Bug, tests

#945 Cmesh parameters with rules
  example/remove/t8_example_empty_trees.cxx
  src/t8_cmesh/t8_cmesh_examples.c
  src/t8_cmesh/t8_cmesh_examples.h
  test/t8_cmesh/t8_gtest_cmesh_set_join_by_vertices.cxx
  test/t8_cmesh_generator/t8_cmesh_example_sets.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_hypercube_pad.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_params.hxx
  test/t8_cmesh_generator/t8_gtest_cmesh_cartestian_product.hxx
  test/t8_geometry/t8_gtest_point_inside.cxx
Labels: enhancement, tests

#957 fix orientation
  src/t8_cmesh/t8_cmesh_examples.c
Labels: Bug, shouldn't take long

#958 Bug fix - Loading cad tree data
  src/t8_geometry/t8_geometry_implementations/t8_geometry_cad.cxx
Labels: Bug

#892 Feature: C-API for Geometry Analytic
  example/geometry/t8_example_geometries.cxx
  src/Makefile.am
  src/t8_geometry/t8_geometry_implementations/t8_geometry_analytic.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_analytic.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_analytic.hxx
Labels: enhancement, examples, shouldn't take long

#796 Improved quadrangulated disk mesh cmesh example [6/n]
  example/cmesh/t8_cmesh_geometry_examples.cxx
  src/t8_cmesh/t8_cmesh_examples.c
  src/t8_cmesh/t8_cmesh_examples.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.hxx
  src/t8_vec.h
Labels: enhancement, examples

#925 Tests: balance forest
  test/Makefile.am
  test/t8_forest/t8_gtest_balance.cxx
Labels: next release
