Repository DLR-AMR/t8code, pull requests merged in 2024-01, with the labels that each got.

#882 Introduce a new Function that checks for equality for 3D vecs
  src/t8_vec.h
  test/t8_gtest_custom_assertion.hxx
  test/t8_gtest_vec.cxx
Labels: enhancement, tests

#891 Added missing `t8_cmesh.h` include in `t8_geometry_with_vertices.h`
  src/t8_geometry/t8_geometry_with_vertices.h
Labels: fix

#840 Remove file
  .gitignore
  example/cmesh/Makefile.am
  example/cmesh/t8_cmesh_refine.cxx
Labels: examples, cleanup

#747 Add an option to use axis-aligned geometry for hex/quad/lines in hype…
  example/cmesh/t8_cmesh_hypercube_pad.cxx
  example/geometry/t8_example_geometries.cxx
  example/remove/t8_example_empty_trees.cxx
  src/t8_cmesh/t8_cmesh_examples.c
  src/t8_cmesh/t8_cmesh_examples.h
  src/t8_geometry/t8_geometry.cxx
  src/t8_geometry/t8_geometry_base.cxx
  src/t8_geometry/t8_geometry_base.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.hxx
  src/t8_geometry/t8_geometry_with_vertices.hxx
  test/t8_cmesh/t8_gtest_cmesh_set_join_by_vertices.cxx
Labels: enhancement, shouldn't take long

#893 Feature set attribute gloidx array
  src/t8_cmesh.h
  src/t8_cmesh/t8_cmesh.c
  test/Makefile.am
  test/t8_cmesh/t8_gtest_attribute_gloidx_array.cxx
Labels: New feature, tests

#767 Feature batch based search
  src/t8_data/t8_containers.cxx
  src/t8_data/t8_containers.h
  src/t8_forest/t8_forest_ghost.cxx
  src/t8_forest/t8_forest_iterate.cxx
  src/t8_forest/t8_forest_iterate.h
  test/t8_forest/t8_gtest_search.cxx
  tutorials/general/t8_tutorial_search.cxx
Labels: enhancement

#788 Add cmesh example cubed spherical shell [3/n].
  example/cmesh/t8_cmesh_geometry_examples.cxx
  src/t8_cmesh/t8_cmesh_examples.c
  src/t8_cmesh/t8_cmesh_examples.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.hxx
Labels: New feature, examples, shouldn't take long, Follow-up PR

#895 Enhancement more const args in get attribute
  src/t8_cmesh.h
  src/t8_cmesh/t8_cmesh.c
  src/t8_cmesh/t8_cmesh_trees.c
  src/t8_cmesh/t8_cmesh_trees.h
Labels: enhancement

#906 Clean up some stuff
  src/t8_forest/t8_forest.c
Labels: shouldn't take long, cleanup

#910 Reduce runtime of tests
  test/t8_forest/t8_gtest_forest_commit.cxx
  test/t8_schemes/t8_gtest_face_descendant.cxx
  test/t8_schemes/t8_gtest_face_neigh.cxx
  test/t8_schemes/t8_gtest_successor.cxx
Labels: tests, fix
