Repository DLR-AMR/t8code, pull requests merged in 2024-08, with the labels that each got.

#1183 Enhancement: Use clang format line ending option for indentation
  .clang-format
  api/Makefile.am
  api/t8_fortran_interface/t8_fortran_interface.c
  api/t8_fortran_interface/t8_fortran_interface.h
  scripts/find_all_source_files.scp
  src/t8_forest/t8_forest_private.c
  src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.c
  src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_connectivity.c
  src/t8_schemes/t8_default/t8_default_tri/t8_dtri_bits.c
  src/t8_vtk/t8_vtk_writer.hxx
  src/t8_vtk/t8_vtk_writer_helper.hxx
  test/t8_IO/t8_gtest_vtk_writer.cxx
  test/t8_cmesh/t8_gtest_attribute_gloidx_array.cxx
  test/t8_cmesh/t8_gtest_cmesh_set_partition_offsets.cxx
  test/t8_cmesh_generator/t8_cmesh_example_sets.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_bigmesh_param.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_comm.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_disjoint_bricks_param.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_empty.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_from_class_param.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_hypercube_param.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_periodic.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_prism_cake_param.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_params.hxx
  test/t8_cmesh_generator/t8_gtest_cmesh_cartestian_product.hxx
  test/t8_cmesh_generator/t8_gtest_cmesh_generator_test.cxx
  test/t8_cmesh_generator/t8_gtest_cmesh_sum_of_sets.hxx
  test/t8_gtest_custom_assertion.hxx
Labels: enhancement, good first issue, cleanup, priority: high, workload: low

#1180 Simplify geometry computation for triangulated/prismed spheres.
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.cxx
Labels: examples, shouldn't take long, next release, priority: medium, workload: low

#1164 Rename T8_TREE/GHOST_FIRST_ATT to T8_TREE/GHOST_FIRST_ATT_INFO
  src/t8_cmesh/t8_cmesh_partition.cxx
  src/t8_cmesh/t8_cmesh_trees.c
  src/t8_cmesh/t8_cmesh_trees.h
Labels: enhancement, shouldn't take long, cleanup, priority: medium, workload: low

#1189 Adapt CI to changes in docker container
  .github/workflows/tests_t8code_linkage_parallel_debug.yml
  .github/workflows/tests_t8code_linkage_parallel_release.yml
Labels: shouldn't take long, CI

#1196 Fix vtk wo mpi
  src/t8_vtk/t8_vtk_reader.cxx
Labels: Bug, priority: high, workload: low

#1190 Assertion and comments for interpolation functions
  src/t8_geometry/t8_geometry_helpers.c
Labels: enhancement, shouldn't take long, priority: medium, workload: low

#1193 CMake linkage improvements
  .typos.toml
  CMakeLists.txt
  cmake/FindOpenCASCADE.cmake
  cmake/FindOpenCASCADE.license
  doc/CMakeLists.txt
  src/CMakeLists.txt
  test/CMakeLists.txt
Labels: fix, priority: medium, workload: low

#1211 Get the username of the user interacting with an issue
  .github/workflows/mattermost_issue.yml
Labels: CI, priority: low, workload: low

#1150 Finalize vtk_writer
  benchmarks/ExtremeScaling/bunny.cxx
  benchmarks/time_forest_partition.cxx
  benchmarks/time_partition.cxx
  example/IO/cmesh/gmsh/t8_read_msh_file.cxx
  example/IO/cmesh/t8_cmesh_load_save.cxx
  example/IO/cmesh/tetgen/t8_forest_from_tetgen.cxx
  example/IO/cmesh/tetgen/t8_read_tetgen_file.cxx
  example/IO/cmesh/triangle/t8_read_triangle_file.cxx
  example/IO/cmesh/vtk/t8_cmesh_read_from_vtk.cxx
  example/advect/t8_advection.cxx
  example/cmesh/t8_cmesh_create_partitioned.cxx
  example/cmesh/t8_cmesh_geometry_examples.cxx
  example/cmesh/t8_cmesh_hypercube_pad.cxx
  example/cmesh/t8_cmesh_partition.cxx
  example/forest/t8_test_face_iterate.cxx
  example/forest/t8_test_ghost.cxx
  example/forest/t8_test_ghost_large_level_diff.cxx
  src/CMakeLists.txt
  src/Makefile.am
  src/t8_cmesh/t8_cmesh_vtk_writer.c
  src/t8_cmesh_vtk_writer.h
  src/t8_forest/t8_forest.cxx
  src/t8_forest/t8_forest_to_vtkUnstructured.hxx
  src/t8_vtk/t8_vtk_write_ASCII.cxx
  src/t8_vtk/t8_vtk_write_ASCII.hxx
  src/t8_vtk/t8_vtk_writer.cxx
  src/t8_vtk/t8_vtk_writer.h
  src/t8_vtk/t8_vtk_writer.hxx
  src/t8_vtk/t8_vtk_writer_helper.cxx
  src/t8_vtk/t8_vtk_writer_helper.hxx
  test/t8_IO/t8_gtest_vtk_writer.cxx
  test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_cad.cxx
  test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_lagrange.cxx
  test/t8_geometry/t8_gtest_point_inside.cxx
  tutorials/general/t8_step1_coarsemesh.cxx
  tutorials/general/t8_tutorial_build_cmesh.cxx
Labels: enhancement, Follow-up PR, C++, priority: medium, workload: medium

#1218 Fix copyright notices
  src/t8_cmesh/t8_cmesh_vtk_reader.cxx
  src/t8_cmesh_vtk_reader.hxx
  src/t8_vtk/t8_vtk_parallel.cxx
  src/t8_vtk/t8_vtk_parallel.hxx
  src/t8_vtk/t8_vtk_polydata.cxx
  src/t8_vtk/t8_vtk_polydata.hxx
  src/t8_vtk/t8_vtk_reader.cxx
  src/t8_vtk/t8_vtk_reader.hxx
  src/t8_vtk/t8_vtk_types.h
  src/t8_vtk/t8_vtk_unstructured.cxx
  src/t8_vtk/t8_vtk_unstructured.hxx
  src/t8_vtk/t8_vtk_write_ASCII.cxx
  src/t8_vtk/t8_vtk_write_ASCII.hxx
  src/t8_vtk/t8_vtk_writer.cxx
  src/t8_vtk/t8_vtk_writer.h
  src/t8_vtk/t8_vtk_writer.hxx
  src/t8_vtk/t8_vtk_writer_helper.cxx
  src/t8_vtk/t8_vtk_writer_helper.hxx
  test/t8_IO/t8_gtest_vtk_reader.cxx
  test/t8_IO/t8_gtest_vtk_writer.cxx
  test/t8_cmesh/t8_gtest_bcast.cxx
  test/t8_cmesh/t8_gtest_cmesh_tree_vertices_negative_volume.cxx
  test/t8_cmesh_generator/t8_cmesh_example_sets.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_bigmesh_param.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_comm.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_disjoint_bricks_param.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_empty.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_from_class_param.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_hypercube_pad.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_hypercube_param.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_periodic.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_prism_cake_param.hxx
  test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_params.hxx
  test/t8_cmesh_generator/t8_gtest_cmesh_cartestian_product.hxx
  test/t8_cmesh_generator/t8_gtest_cmesh_generator_test.cxx
  test/t8_cmesh_generator/t8_gtest_cmesh_sum_of_sets.hxx
  test/t8_forest/t8_gtest_balance.cxx
  test/t8_forest/t8_gtest_element_volume.cxx
  test/t8_forest/t8_gtest_forest_face_normal.cxx
  test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_lagrange.cxx
  test/t8_geometry/t8_gtest_point_inside.cxx
  test/t8_gtest_basics.cxx
  test/t8_gtest_custom_assertion.hxx
  test/t8_gtest_eclass.cxx
  test/t8_gtest_macros.hxx
  test/t8_gtest_refcount.cxx
  test/t8_gtest_vec.cxx
  test/t8_gtest_version.cxx
  test/t8_schemes/t8_gtest_ancestor.cxx
  test/t8_schemes/t8_gtest_default.cxx
  test/t8_schemes/t8_gtest_descendant.cxx
  test/t8_schemes/t8_gtest_element_ref_coords.cxx
  test/t8_schemes/t8_gtest_face_descendant.cxx
  test/t8_schemes/t8_gtest_init_linear_id.cxx
  test/t8_schemes/t8_gtest_nca.cxx
  test/t8_schemes/t8_gtest_pyra_connectivity.cxx
  test/t8_schemes/t8_gtest_root.cxx
  test/t8_schemes/t8_gtest_scheme_consistency.cxx
  test/t8_schemes/t8_gtest_successor.cxx
Labels: fix, priority: high, workload: low

#1187 Test t8_geom_triangular_interpolation
  test/CMakeLists.txt
  test/Makefile.am
  test/t8_geometry/t8_gtest_geometry_triangular_interpolation.cxx
Labels: tests, priority: medium, workload: low

#1185 Refactored quad/cubed sphere mesh/geometry.
  example/cmesh/t8_cmesh_geometry_examples.cxx
  src/t8_cmesh/t8_cmesh_examples.cxx
  src/t8_cmesh/t8_cmesh_examples.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.hxx
  src/t8_vec.h
  test/t8_geometry/t8_gtest_geometry_handling.cxx
Labels: enhancement, examples, next release, fix, priority: medium, workload: low

#1208 Improve search callback
  src/t8_forest/t8_forest_ghost.cxx
  src/t8_forest/t8_forest_iterate.cxx
  src/t8_forest/t8_forest_iterate.h
  test/t8_forest/t8_gtest_search.cxx
  tutorials/general/t8_tutorial_search.cxx
Labels: priority: medium, workload: low

#1217 Add tree compatibility test for example cmesh geoms
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.hxx
Labels: enhancement, help wanted, shouldn't take long, priority: medium, workload: low

#1222 Fix a warning
  src/t8_vtk/t8_vtk_writer_helper.hxx
Labels: shouldn't take long, fix, priority: low, workload: low

#1223 Fix various warnings
  src/t8_cmesh/t8_cmesh_geometry.cxx
  src/t8_cmesh/t8_cmesh_partition.cxx
  src/t8_cmesh/t8_cmesh_readmshfile.cxx
  src/t8_cmesh/t8_cmesh_triangle.cxx
  src/t8_forest/t8_forest_ghost.cxx
  src/t8_forest/t8_forest_partition.cxx
  src/t8_geometry/t8_geometry_base.hxx
  src/t8_geometry/t8_geometry_handler.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_analytic.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_zero.hxx
  src/t8_schemes/t8_default/t8_default_common/t8_default_common.hxx
Labels: shouldn't take long, cleanup, priority: medium, workload: low

#1216 Add api folder to indent all files script
  scripts/indent_all_files.scp
Labels: shouldn't take long, fix, priority: low, workload: low

#1212 only search for components of the vtk library
  CMakeLists.txt
Labels: shouldn't take long, priority: low, workload: low

#1228 Add a default value to run the test-suite 2
  CMakeLists.txt
  test/CMakeLists.txt
Labels: tests, priority: low, priority: medium, CMake

#1199 CMake CI [1.5/2]
  .github/workflows/tests_cmake_t8code.yml
  .github/workflows/tests_cmake_testsuite.yml
Labels: CI, priority: medium, workload: low

#1200 CMake CI [2/2]
  .github/workflows/tests_cmake_t8code_linkage.yml
  .github/workflows/tests_cmake_testsuite.yml
  CMakeLists.txt
Labels: CI, draft, Follow-up PR, priority: medium, workload: low

#1233 Fix a typo
  pull_request_template.md
Labels: shouldn't take long, Typos, priority: low, workload: low

#1226 Enable parallel tests in cmake ci
  .github/workflows/tests_cmake_sc_p4est.yml
  .github/workflows/tests_cmake_t8code.yml
  .github/workflows/tests_cmake_t8code_linkage.yml
Labels: shouldn't take long, CI, Follow-up PR, priority: medium, workload: low

#1234 Revert "Enable parallel tests in cmake ci"
  .github/workflows/tests_cmake_sc_p4est.yml
  .github/workflows/tests_cmake_t8code.yml
  .github/workflows/tests_cmake_t8code_linkage.yml
Labels: shouldn't take long, CI, critical, priority: high, workload: low, CMake

#1229 Enhance default build type selection
  CMakeLists.txt
Labels: enhancement, shouldn't take long, priority: low, workload: low, CMake

#1239 Minor typo fixes and enhancements
  test/t8_cmesh/t8_gtest_hypercube.cxx
  test/t8_forest/t8_gtest_element_volume.cxx
  test/t8_forest/t8_gtest_forest_commit.cxx
Labels: enhancement, shouldn't take long, Typos, priority: low, workload: low
