Repository DLR-AMR/t8code, pull requests merged in 2024-05, with the labels that each got.

#1039 Enhancement: speed-up `t8_cmesh_set_join_by_vertices`.
  benchmarks/t8_time_set_join_by_vertices.cxx
  src/Makefile.am
  src/t8_cmesh/t8_cmesh_helpers.c
  src/t8_cmesh/t8_cmesh_helpers.cxx
  src/t8_cmesh/t8_cmesh_helpers.h
Labels: enhancement

#1060 Fix typo
  test/t8_cmesh/t8_gtest_hypercube.cxx
Labels: shouldn't take long, good first issue, Typos

#1045 Set join by stash
  src/t8_cmesh/t8_cmesh_helpers.cxx
  src/t8_cmesh/t8_cmesh_helpers.h
Labels: enhancement

#1044 Add an rc to geom_handler
  src/t8_cmesh/t8_cmesh.cxx
  src/t8_cmesh/t8_cmesh_commit.cxx
  src/t8_geometry/t8_geometry_handler.hxx
Labels: fix

#1037 Revert "Rename element ref coords integer coords" partially
  src/t8_schemes/t8_default/t8_default_common/t8_default_common_cxx.hxx
  src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.cxx
  src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.hxx
  src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.cxx
  src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.hxx
  src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.cxx
  src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.hxx
  src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.cxx
  src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.hxx
  src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.cxx
  src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.hxx
  src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.cxx
  src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.hxx
  src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.cxx
  src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.hxx
  src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.cxx
  src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.hxx
Labels: fix

#971 Feature curved prisms
  src/t8_cmesh/t8_cmesh_readmshfile.cxx
  src/t8_eclass.c
  src/t8_geometry/t8_geometry_helpers.c
  src/t8_geometry/t8_geometry_helpers.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_cad.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_cad.hxx
  src/t8_schemes/t8_default/t8_default_prism/t8_dprism.h
Labels: New feature

#1076 /f$ -> \f$ for latex documentation
  example/geometry/t8_example_geometries.cxx
  src/t8_geometry/t8_geometry_base.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_analytic.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_analytic.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_cad.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear_axis_aligned.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_zero.hxx
Labels: documentation, Typos

#1074 Add doxygen generation to cmake
  CMakeLists.txt
  doc/CMakeLists.txt
  doc/Doxyfile.in
  src/CMakeLists.txt
Labels: documentation
