Repository DLR-AMR/t8code, pull requests merged in 2024-04, with the labels that each got.

#1008 Update typos
  doc/Doxyfile.in
  example/IO/forest/netcdf/t8_write_forest_netcdf.cxx
  src/t8_cmesh/t8_cmesh_examples.cxx
  src/t8_cmesh/t8_cmesh_partition.cxx
  src/t8_geometry/t8_geometry_helpers.c
  src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.c
  src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.h
  test/t8_cmesh/t8_gtest_cmesh_set_partition_offsets.cxx
  test/t8_schemes/t8_gtest_ancestor.cxx
Labels: Typos

#832 Rename element ref coords integer coords
  src/t8_schemes/t8_default/t8_default_common/t8_default_common_cxx.hxx
  src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.cxx
  src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.hxx
  src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.cxx
  src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.hxx
  src/t8_schemes/t8_default/t8_default_line/t8_dline_bits.c
  src/t8_schemes/t8_default/t8_default_line/t8_dline_bits.h
  src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.cxx
  src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.hxx
  src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.c
  src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.h
  src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.cxx
  src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.hxx
  src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.c
  src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.h
  src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.cxx
  src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.hxx
  src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.cxx
  src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.hxx
  src/t8_schemes/t8_default/t8_default_tet/t8_dtet_bits.h
  src/t8_schemes/t8_default/t8_default_tet/t8_dtri_to_dtet.h
  src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.cxx
  src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.hxx
  src/t8_schemes/t8_default/t8_default_tri/t8_dtri_bits.c
  src/t8_schemes/t8_default/t8_default_tri/t8_dtri_bits.h
  src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.cxx
  src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.hxx
  src/t8_schemes/t8_default/t8_default_vertex/t8_dvertex_bits.c
  src/t8_schemes/t8_default/t8_default_vertex/t8_dvertex_bits.h
Labels: enhancement, shouldn't take long, next release

#1033 Renamed uints to the more commong uint32_t datatype.
  src/t8_geometry/t8_geometry_implementations/t8_geometry_lagrange.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_lagrange.hxx
  test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_lagrange.cxx
Labels: enhancement, fix

#1034 Remove `bool` keyword from C header files
  src/t8_cmesh.h
  src/t8_cmesh/t8_cmesh.cxx
  src/t8_geometry/t8_geometry.cxx
  src/t8_geometry/t8_geometry.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_analytic.h
Labels: shouldn't take long, good first issue, next release, fix

#1010 Add enable-fortran
  configure.ac
Labels: shouldn't take long, good first issue

#1040 Adapt short cli argument of advection solver to cad rename
  example/advect/t8_advection.cxx
Labels: shouldn't take long, fix

#1021 Feature: Optionally compute face orientation when calling leaf_face_neighbor routine.
  src/t8_forest/t8_forest_cxx.cxx
  src/t8_forest/t8_forest_general.h
  test/t8_forest/t8_gtest_forest_face_normal.cxx
Labels: enhancement, shouldn't take long, good first issue

#997 cmake: Add option to use system sc and p4est
  CMakeLists.txt
Labels: enhancement

#1046 Add a \n
  src/t8_cmesh/t8_cmesh_readmshfile.cxx
Labels: shouldn't take long, Typos

#1007 Test geometry cad tets
  test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_cad.cxx
Labels: enhancement, tests

#1051 Fix mattermost bot
  .github/workflows/mattermost.yml
Labels: shouldn't take long, fix
