Repository DLR-AMR/t8code, pull requests merged in 2024-10, with the labels that each got.

#1257 Add write_element_id to initializer-list
  src/t8_vtk/t8_vtk_writer.hxx
Labels: Bug, fix, priority: high, workload: low

#1255 Build Fortran interface: autotools & CMake
  .github/workflows/tests_cmake_t8code_api.yml
  .github/workflows/tests_cmake_testsuite.yml
  .gitignore
  CMakeLists.txt
  Makefile.am
  api/Makefile.am
  api/t8_fortran_interface/CMakeLists.txt
  api/t8_fortran_interface/t8_fortran_interface.c
  api/t8_fortran_interface/t8_fortran_interface.h
  api/t8_fortran_interface/t8_fortran_interface_mod.f90
  api/t8_fortran_interface/t8_fortran_specific.mk
  cmake/FindOpenCASCADE.cmake
  config/t8_fortran.m4
  test/CMakeLists.txt
  test/api/t8_fortran_interface/t8_test_mpi_init.f90
Labels: next release, priority: high, workload: medium, Fortran, CMake

#1258 Allow more clang-format versions
  scripts/t8indent
Labels: enhancement, shouldn't take long, priority: low, workload: low

#1262 Cleanup tutorial build cmesh
  doc/author_albers.txt
  tutorials/general/t8_tutorial_build_cmesh.cxx
Labels: cleanup, workload: low

#1215 Remove dimensionality of geoms
  example/geometry/t8_example_geometries.cxx
  src/t8_cmesh/t8_cmesh_cad.cxx
  src/t8_cmesh/t8_cmesh_examples.cxx
  src/t8_cmesh/t8_cmesh_examples.h
  src/t8_cmesh/t8_cmesh_readmshfile.cxx
  src/t8_cmesh/t8_cmesh_triangle.cxx
  src/t8_geometry/t8_geometry_base.cxx
  src/t8_geometry/t8_geometry_base.h
  src/t8_geometry/t8_geometry_base.hxx
  src/t8_geometry/t8_geometry_handler.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_analytic.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_analytic.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_analytic.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_cad.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_cad.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_cad.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_lagrange.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_lagrange.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_lagrange.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear_axis_aligned.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear_axis_aligned.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear_axis_aligned.hxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_zero.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_zero.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_zero.hxx
  src/t8_geometry/t8_geometry_with_vertices.hxx
  src/t8_vtk/t8_vtk_reader.cxx
  test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_cad.cxx
  test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_lagrange.cxx
  test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_linear.cxx
  test/t8_geometry/t8_gtest_geometry_handling.cxx
  test/t8_geometry/t8_gtest_point_inside.cxx
  tutorials/general/t8_tutorial_build_cmesh.cxx
Labels: enhancement, Follow-up PR, priority: low, workload: low

#1265 Use looser indent-script condition for all indent scripts
  scripts/check_if_file_indented.scp
Labels: enhancement, priority: high, workload: low

#1272 Correct documentation of t8_forest_leaf_face_neighbors.
  src/t8_forest/t8_forest_general.h
Labels: documentation, priority: low, workload: low

#1270 Properly exclude files with typos in pre-commit hook
  scripts/pre-commit
Labels: enhancement, priority: low, workload: low

#1275 Fix an assertion
  src/t8_forest/t8_forest_iterate.cxx
Labels: shouldn't take long, fix, priority: low, workload: low

#1285 Fix wrong return value when checking tree geometry compat.
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.hxx
Labels: Bug, fix, priority: high, workload: low
