Repository DLR-AMR/t8code, pull requests merged in 2024-06, with the labels that each got.

#1062 Fix negative volume in quadr. disk & cubed sphere.
  example/cmesh/t8_cmesh_geometry_examples.cxx
  src/t8_cmesh/t8_cmesh_examples.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.cxx
Labels: enhancement, examples, fix

#1057 Addition: Getter function for cmesh & forest dimension
  src/t8_cmesh.h
  src/t8_cmesh/t8_cmesh.cxx
  src/t8_forest/t8_forest_cxx.cxx
  src/t8_forest/t8_forest_geometrical.h
  test/t8_cmesh/t8_gtest_hypercube.cxx
  test/t8_forest/t8_gtest_element_volume.cxx
Labels: New feature, shouldn't take long, good first issue

#1079 More const parameter for our element array class [1/3].
  src/t8_data/t8_containers.cxx
  src/t8_data/t8_containers.h
  src/t8_forest/t8_forest.c
  src/t8_forest/t8_forest_adapt.cxx
  src/t8_forest/t8_forest_cxx.cxx
  src/t8_forest/t8_forest_ghost.cxx
  src/t8_forest/t8_forest_iterate.cxx
  src/t8_forest/t8_forest_partition.cxx
  src/t8_forest/t8_forest_private.c
  src/t8_forest/t8_forest_private.h
Labels: enhancement

#1080 element is leaf and forest is local checks [2/3]
  src/t8_forest/t8_forest.c
  src/t8_forest/t8_forest_cxx.cxx
  src/t8_forest/t8_forest_general.h
  src/t8_forest/t8_forest_iterate.cxx
  test/CMakeLists.txt
  test/Makefile.am
  test/t8_forest/t8_gtest_element_is_leaf.cxx
Labels: enhancement, Follow-up PR

#1092 Fix documentation
  .github/workflows/add_release_documentation.yml
  .github/workflows/update_documentation.yml
Labels: CI, fix

#1091 Add sudo apt-get update && sudo apt-get upgrade -y to all actions
  .github/workflows/add_release_documentation.yml
  .github/workflows/check_indentation.yml
  .github/workflows/ci_playground.yml
  .github/workflows/test_tarball.yml
  .github/workflows/tests_sc_p4est.yml
  .github/workflows/tests_t8code_linkage_parallel_debug.yml
  .github/workflows/tests_t8code_linkage_parallel_release.yml
  .github/workflows/tests_t8code_parallel.yml
  .github/workflows/tests_t8code_serial.yml
  .github/workflows/update_documentation.yml
Labels: enhancement, CI

#1071 Catch and fix negative volumes of triangles/quads in 2D Gmsh files.
  src/t8_cmesh/t8_cmesh.cxx
  src/t8_cmesh/t8_cmesh_readmshfile.cxx
Labels: enhancement, shouldn't take long, tests, good first issue

#1069 CMake: added CMake export config file
  doc/author_karembe.txt
  src/CMakeLists.txt
  src/config.cmake.in
Labels: enhancement, draft

#1072 Fix incorrect installed public header tree hierarchy
  src/CMakeLists.txt
Labels: fix

#1075 Sphinx documentation
  CMakeLists.txt
  cmake/FindSphinx.cmake
  doc/CMakeLists.txt
  doc/Doxyfile.in
  doc/source/conf.in
  doc/source/index.rst
  src/t8_forest/t8_forest_private.h
Labels: documentation

#1084 Add the exhale extension to sphinx for a better structured documentation
  doc/CMakeLists.txt
  doc/source/conf.in
  doc/source/index.rst
Labels: documentation, Follow-up PR
