Repository DLR-AMR/t8code, pull requests merged in 2025-01, with the labels that each got.

#1332 Correct typos
  example/advect/t8_advection.cxx
  test/t8_cmesh_generator/t8_gtest_cmesh_cartestian_product.hxx
  test/t8_forest/t8_gtest_partition_data.cxx
  test/t8_gtest_vec.cxx
Labels: shouldn't take long, Typos, priority: high, workload: low, tag: patch

#1334 Update element-functions
  .github/workflows/tests_cmake_t8code_api.yml
  api/t8_fortran_interface/t8_fortran_interface.c
Labels: Bug, shouldn't take long, critical, priority: high, workload: low, Fortran, tag: patch

#1290 Remove code duplication
  src/t8_schemes/t8_default/t8_default_tet/t8_dtet_connectivity.c
  src/t8_schemes/t8_default/t8_default_tet/t8_dtet_connectivity.h
  src/t8_schemes/t8_default/t8_default_tri/t8_dtri_connectivity.c
  src/t8_schemes/t8_default/t8_default_tri/t8_dtri_connectivity.h
Labels: Bug, cleanup, priority: low, workload: low

#1336 fixed missing Assertion
  test/t8_gtest_custom_assertion.hxx
  test/t8_schemes/t8_gtest_face_neigh.cxx
  test/t8_schemes/t8_gtest_successor.cxx
Labels: shouldn't take long, tests, cleanup, priority: low, workload: low, tag: patch

#1341 Add getter for scheme eclass
  src/t8_schemes/t8_default/t8_default_common/t8_default_common.hxx
  src/t8_schemes/t8_scheme.hxx
Labels: enhancement, shouldn't take long, priority: medium, workload: low

#1343 Remove duplicate declaration
  src/t8_vtk/t8_vtk_writer.h
Labels: shouldn't take long, good first issue, cleanup, priority: medium, workload: low, patch-release

#1347 Avoid dynamic allocation in element-functions
  src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.c
  src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.c
Labels: enhancement, shouldn't take long, priority: low, workload: low, patch-release

#1348 Avoid dynamic allocations with hard-coded numbers
  src/t8_cmesh/t8_cmesh_commit.cxx
  src/t8_forest/t8_forest_netcdf.cxx
Labels: enhancement, shouldn't take long, priority: low, workload: low, patch-release

#1339 Fix dquad/pquad confusion bug
  src/CMakeLists.txt
  src/t8_schemes/t8_default/t8_default_quad/t8_default_quad.cxx
  src/t8_schemes/t8_default/t8_default_quad/t8_default_quad.hxx
  src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_bits.cxx
  src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_bits.hxx
  src/t8_schemes/t8_default/t8_default_quad/t8_dquad.h
Labels: patch-release

#1346 Add element ancestor test
  src/t8_schemes/t8_default/t8_default_hex/t8_default_hex.hxx
  src/t8_schemes/t8_default/t8_default_line/t8_default_line.hxx
  src/t8_schemes/t8_default/t8_default_prism/t8_default_prism.hxx
  src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid.hxx
  src/t8_schemes/t8_default/t8_default_quad/t8_default_quad.hxx
  src/t8_schemes/t8_default/t8_default_tet/t8_default_tet.hxx
  src/t8_schemes/t8_default/t8_default_tri/t8_default_tri.hxx
  src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex.hxx
  src/t8_schemes/t8_scheme.hxx
  test/CMakeLists.txt
  test/t8_schemes/t8_gtest_ancestor.cxx
  test/t8_schemes/t8_gtest_ancestor_id.cxx
Labels: tests, priority: low, workload: low

#1349 Make all schemes const
  api/t8_fortran_interface/t8_fortran_interface.c
  benchmarks/time_forest_partition.cxx
  example/IO/forest/netcdf/t8_write_forest_netcdf.cxx
  example/advect/t8_advection.cxx
  example/cmesh/t8_cmesh_hypercube_pad.cxx
  src/t8_cmesh.h
  src/t8_cmesh/t8_cmesh.cxx
  src/t8_cmesh/t8_cmesh_partition.cxx
  src/t8_cmesh/t8_cmesh_types.h
  src/t8_forest/t8_forest.cxx
  src/t8_forest/t8_forest_adapt.cxx
  src/t8_forest/t8_forest_balance.cxx
  src/t8_forest/t8_forest_general.h
  src/t8_forest/t8_forest_ghost.cxx
  src/t8_forest/t8_forest_iterate.cxx
  src/t8_forest/t8_forest_partition.cxx
  src/t8_forest/t8_forest_private.h
  src/t8_forest/t8_forest_types.h
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear.cxx
  src/t8_schemes/t8_default/t8_default.cxx
  src/t8_schemes/t8_default/t8_default.hxx
  src/t8_schemes/t8_default/t8_default_c_interface.h
  src/t8_schemes/t8_scheme.hxx
  src/t8_schemes/t8_scheme_builder.hxx
  test/t8_IO/t8_gtest_vtk_writer.cxx
  test/t8_forest/t8_gtest_balance.cxx
  test/t8_forest/t8_gtest_element_is_leaf.cxx
  test/t8_forest/t8_gtest_element_volume.cxx
  test/t8_forest/t8_gtest_find_owner.cxx
  test/t8_forest/t8_gtest_forest_commit.cxx
  test/t8_forest/t8_gtest_forest_face_normal.cxx
  test/t8_forest/t8_gtest_ghost_and_owner.cxx
  test/t8_forest/t8_gtest_ghost_delete.cxx
  test/t8_forest/t8_gtest_ghost_exchange.cxx
  test/t8_forest/t8_gtest_half_neighbors.cxx
  test/t8_forest/t8_gtest_partition_data.cxx
  test/t8_forest/t8_gtest_search.cxx
  test/t8_forest/t8_gtest_transform.cxx
  test/t8_forest/t8_gtest_user_data.cxx
  test/t8_forest_incomplete/t8_gtest_recursive.cxx
  test/t8_geometry/t8_gtest_point_inside.cxx
  test/t8_gtest_schemes.hxx
  test/t8_schemes/t8_gtest_ancestor.cxx
  test/t8_schemes/t8_gtest_default.cxx
  test/t8_schemes/t8_gtest_descendant.cxx
  test/t8_schemes/t8_gtest_dfs_base.hxx
  test/t8_schemes/t8_gtest_element_count_leaves.cxx
  test/t8_schemes/t8_gtest_face_neigh.cxx
  test/t8_schemes/t8_gtest_init_linear_id.cxx
  test/t8_schemes/t8_gtest_nca.cxx
  test/t8_schemes/t8_gtest_root.cxx
  test/t8_schemes/t8_gtest_successor.cxx
  tutorials/general/t8_step2_uniform_forest.cxx
  tutorials/general/t8_step5_element_data.cxx
  tutorials/general/t8_step5_element_data_c_interface.c
  tutorials/general/t8_step6_stencil.cxx
  tutorials/general/t8_step7_interpolation.cxx
Labels: enhancement, workload: low, major-release

#1356 Revert loop to prevent overwriting of the input element
  src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.c
Labels: shouldn't take long, priority: low, workload: low, patch-release

#1344 Fix benchmarks
  benchmarks/CMakeLists.txt
  benchmarks/t8_time_forest_partition.cxx
  benchmarks/t8_time_new_refine.c
  benchmarks/t8_time_partition.cxx
  benchmarks/time_refine_type03.c
Labels: fix, priority: low, workload: low

#1297 Feature search cpp interface
  src/CMakeLists.txt
  src/t8_forest/t8_forest.cxx
  src/t8_forest/t8_forest_search/t8_forest_search.cxx
  src/t8_forest/t8_forest_search/t8_forest_search.h
  src/t8_forest/t8_forest_search/t8_forest_search.hxx
  test/t8_forest/t8_gtest_search.cxx
Labels: minor-release

#1352 Test all schemes in forest tests
  test/t8_cmesh/t8_gtest_cmesh_partition.cxx
  test/t8_cmesh/t8_gtest_multiple_attributes.cxx
  test/t8_cmesh_generator/t8_cmesh_example_sets.hxx
  test/t8_forest/t8_gtest_balance.cxx
  test/t8_forest/t8_gtest_element_is_leaf.cxx
  test/t8_forest/t8_gtest_element_volume.cxx
  test/t8_forest/t8_gtest_find_owner.cxx
  test/t8_forest/t8_gtest_forest_commit.cxx
  test/t8_forest/t8_gtest_forest_face_normal.cxx
  test/t8_forest/t8_gtest_ghost_and_owner.cxx
  test/t8_forest/t8_gtest_ghost_delete.cxx
  test/t8_forest/t8_gtest_ghost_exchange.cxx
  test/t8_forest/t8_gtest_half_neighbors.cxx
  test/t8_forest/t8_gtest_partition_data.cxx
  test/t8_forest/t8_gtest_search.cxx
  test/t8_forest/t8_gtest_transform.cxx
  test/t8_forest/t8_gtest_user_data.cxx
  test/t8_gtest_schemes.hxx
  test/t8_schemes/t8_gtest_boundary_extrude.cxx
  test/t8_schemes/t8_gtest_child_parent_face.cxx
  test/t8_schemes/t8_gtest_face_descendant.cxx
  test/t8_schemes/t8_gtest_face_neigh.cxx
Labels: priority: high, workload: low, patch-release

#1363 Test input = output
  test/CMakeLists.txt
  test/t8_schemes/t8_gtest_input_equal_output.cxx
Labels: workload: low, patch-release
