Repository DLR-AMR/t8code, pull requests merged in 2025-06, with the labels that each got.

#1696 Bugfix: Wrong vector operations in benchmark
  benchmarks/t8_time_forest_partition.cxx
Labels: priority:high, workload:low

#1694 Fix typo in documentation
  src/t8_types/t8_vec.hxx
Labels: shouldn't take long, Typos, priority:low, workload:low

#1701 Fix: CI updates run into 403 error.
  .github/workflows/code_coverage.yml
  .github/workflows/tests_cmake_preparation.yml
  .github/workflows/tests_cmake_sc_p4est.yml
  .github/workflows/tests_cmake_t8code.yml
  .github/workflows/tests_cmake_t8code_api.yml
  .github/workflows/tests_cmake_t8code_linkage.yml
  .github/workflows/tests_cmake_t8code_w_shipped_submodules.yml
  .github/workflows/tests_cmake_valgrind.yml
Labels: CI, critical, priority:high, workload:low

#1224 Pack/Unpack data for user-data
  config/t8_vtk.m4
  src/Makefile.am
  src/t8_data/t8_data_handler.hxx
  src/t8_data/t8_vector_handler.hxx
  src/t8_types/t8_data_handler_type.hxx
  src/t8_types/t8_operators.hxx
  test/CMakeLists.txt
  test/t8_data/t8_data_handler_specs.cxx
  test/t8_data/t8_data_handler_specs.hxx
  test/t8_data/t8_enlarged_stdtypes.hxx
  test/t8_data/t8_gtest_data_handler.cxx
  test/t8_data/t8_pseudo_trees.hxx
Labels: New feature, priority:low, workload:medium

#1717 Fix: Use testsuite alloc
  test/t8_cmesh/t8_gtest_cmesh_vertex_conn_tree_to_vertex.cxx
Labels: shouldn't take long, priority:low, workload:low
