Repository DLR-AMR/t8code, pull requests merged in 2025-05, with the labels that each got.

#1602 Improvement: Remove package update in indent workflow
  .github/workflows/build_cmake_tarball.yml
  .github/workflows/check_indentation.yml
Labels: priority:low, workload:low

#960 Feature cmesh vertex connectivity
  src/CMakeLists.txt
  src/Makefile.am
  src/t8_cmesh/t8_cmesh.cxx
  src/t8_cmesh/t8_cmesh_commit.cxx
  src/t8_cmesh/t8_cmesh_types.h
  src/t8_cmesh/t8_cmesh_vertex_connectivity/t8_cmesh_vertex_conn_tree_to_vertex.cxx
  src/t8_cmesh/t8_cmesh_vertex_connectivity/t8_cmesh_vertex_conn_tree_to_vertex.hxx
  src/t8_cmesh/t8_cmesh_vertex_connectivity/t8_cmesh_vertex_conn_vertex_to_tree.cxx
  src/t8_cmesh/t8_cmesh_vertex_connectivity/t8_cmesh_vertex_conn_vertex_to_tree.hxx
  src/t8_cmesh/t8_cmesh_vertex_connectivity/t8_cmesh_vertex_connectivity.cxx
  src/t8_cmesh/t8_cmesh_vertex_connectivity/t8_cmesh_vertex_connectivity.h
  src/t8_cmesh/t8_cmesh_vertex_connectivity/t8_cmesh_vertex_connectivity.hxx
  test/CMakeLists.txt
  test/Makefile.am
  test/t8_cmesh/t8_gtest_cmesh_vertex_conn.cxx
  test/t8_cmesh/t8_gtest_cmesh_vertex_conn_tree_to_vertex.cxx
  test/t8_cmesh/t8_gtest_cmesh_vertex_conn_vertex_to_tree.cxx
Labels: New feature

#1596 Scheme improvements
  src/t8_schemes/t8_default/t8_default_common/t8_default_common.hxx
  src/t8_schemes/t8_default/t8_default_hex/t8_default_hex.hxx
  src/t8_schemes/t8_default/t8_default_line/t8_default_line.hxx
  src/t8_schemes/t8_default/t8_default_prism/t8_default_prism.hxx
  src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid.hxx
  src/t8_schemes/t8_default/t8_default_quad/t8_default_quad.hxx
  src/t8_schemes/t8_default/t8_default_tet/t8_default_tet.hxx
  src/t8_schemes/t8_default/t8_default_tri/t8_default_tri.hxx
  src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex.hxx
  src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
Labels: enhancement, shouldn't take long, priority:low, workload:low

#1620 Bugfix: Missing utility header include
  src/t8_schemes/t8_default/t8_default_common/t8_default_common.hxx
  src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
Labels: Bug, shouldn't take long, critical, priority:high, workload:low

#1423 Rework msh reader
  src/t8_cmesh/t8_cmesh_readmshfile.cxx
  src/t8_cmesh_readmshfile.h
Labels: enhancement, priority:medium, workload:low

#1626 Other: Remove deprecated indent macro
  src/t8_geometry/t8_geometry_implementations/t8_geometry_cad.cxx
  test/t8_geometry/t8_gtest_point_inside.cxx
Labels: shouldn't take long, priority:low, workload:low

#1397 Add global vertex id to msh file reader
  src/t8_cmesh/t8_cmesh_readmshfile.cxx
Labels: enhancement, Follow-up PR, priority:low, workload:low

#1475 Bugfix: msh node conversion tables
  src/t8_cmesh/t8_cmesh_readmshfile.cxx
Labels: Bug, shouldn't take long, priority:medium, workload:low

#1516 Bugfix: CMake Install paths
  CMakeLists.txt
  benchmarks/CMakeLists.txt
  example/CMakeLists.txt
  src/CMakeLists.txt
  tutorials/CMakeLists.txt
Labels: priority:medium, workload:medium, CMake

#1662 Feature: strong type conversion [1/2]
  src/t8_types/t8_type.hxx
  test/t8_types/t8_gtest_type.cxx
Labels: enhancement, priority:medium, workload:low
