Repository DLR-AMR/t8code, pull requests merged in 2025-02, with the labels that each got.

#1358 introduce more setters to the vtk writer
  src/t8_vtk/t8_vtk_writer.hxx
Labels: enhancement, good first issue, priority: low, workload: low

#1382 Correct order of execution in docu and some typos
  doc/author_ploetzke.txt
  src/t8_forest/t8_forest_general.h
  tutorials/general/t8_step2_uniform_forest.cxx
  tutorials/general/t8_step3_adapt_forest.cxx
  tutorials/general/t8_step4_partition_balance_ghost.cxx
  tutorials/general/t8_step5_element_data.cxx
Labels: shouldn't take long, documentation, cleanup, priority: low, workload: low, patch-release

#1387 Adding link to JOSS paper in README.md.
  README.md
Labels: shouldn't take long, priority: low, workload: low, patch-release

#1309 Strong types
  src/CMakeLists.txt
  src/t8_schemes/t8_crtp.hxx
  src/t8_schemes/t8_default/t8_default_common/t8_default_common.hxx
  src/t8_types/t8_operators.hxx
  src/t8_types/t8_type.hxx
  test/CMakeLists.txt
  test/t8_types/t8_gtest_type.cxx
Labels: enhancement, C++, priority: medium, workload: medium

#1393 Update all github-runners to ubuntu-22.04
  .github/workflows/build_cmake_tarball.yml
  .github/workflows/check_indentation.yml
  .github/workflows/mattermost_issue.yml
  .github/workflows/mattermost_pull_request.yml
Labels: shouldn't take long, priority: high, patch-release

#1394 Update GitHub Runners
  .github/workflows/build_cmake_tarball.yml
  .github/workflows/check_indentation.yml
  .github/workflows/mattermost_issue.yml
  .github/workflows/mattermost_pull_request.yml
Labels: CI, priority: high, workload: low

#1380 Add new test for linear id
  src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
  test/CMakeLists.txt
  test/t8_schemes/t8_gtest_bfs_base.hxx
  test/t8_schemes/t8_gtest_get_linear_id.cxx
  test/t8_schemes/t8_gtest_set_linear_id.cxx
Labels: draft, fix, workload: low, patch-release

#1399 Improvements to the tutorials
  tutorials/general/t8_step1_coarsemesh.cxx
  tutorials/general/t8_step2_uniform_forest.cxx
  tutorials/general/t8_step3_adapt_forest.cxx
  tutorials/general/t8_step6_stencil.cxx
  tutorials/general/t8_step7_interpolation.cxx
  tutorials/general/t8_tutorial_build_cmesh.cxx
  tutorials/general/t8_tutorial_search.cxx
Labels: cleanup

#1402 fix typos
  doc/Doxyfile.in
  src/t8_forest/t8_forest_ghost.cxx
Labels: cleanup, Typos, priority: high, workload: low

#1359 Scheme tutorial
  tutorials/CMakeLists.txt
  tutorials/general/t8_tutorial_build_scheme.cxx
Labels: next release, Follow-up PR

#1413 Replaced ENABLE_LESS_TESTS by TEST_LEVEL
  .github/workflows/add_release_documentation.yml
  .github/workflows/build_cmake_tarball.yml
  .github/workflows/tests_cmake_t8code.yml
  .github/workflows/tests_cmake_t8code_api.yml
  .github/workflows/tests_cmake_t8code_linkage.yml
  .github/workflows/tests_cmake_t8code_w_shipped_submodules.yml
  .github/workflows/tests_cmake_testsuite.yml
  .github/workflows/update_documentation.yml
  CMakeLists.txt
  src/CMakeLists.txt
  test/CMakeLists.txt
  test/t8_cmesh_generator/t8_cmesh_parameterized_examples/t8_cmesh_params.hxx
  test/t8_forest/t8_gtest_balance.cxx
  test/t8_forest/t8_gtest_element_is_leaf.cxx
  test/t8_forest_incomplete/t8_gtest_iterate_replace.cxx
  test/t8_forest_incomplete/t8_gtest_permute_hole.cxx
  test/t8_geometry/t8_gtest_point_inside.cxx
  test/t8_gtest_macros.hxx
  test/t8_schemes/t8_gtest_ancestor_id.cxx
  test/t8_schemes/t8_gtest_boundary_extrude.cxx
  test/t8_schemes/t8_gtest_child_parent_face.cxx
  test/t8_schemes/t8_gtest_element_ref_coords.cxx
  test/t8_schemes/t8_gtest_equal.cxx
  test/t8_schemes/t8_gtest_face_descendant.cxx
  test/t8_schemes/t8_gtest_face_neigh.cxx
  test/t8_schemes/t8_gtest_find_parent.cxx
  test/t8_schemes/t8_gtest_get_linear_id.cxx
  test/t8_schemes/t8_gtest_input_equal_output.cxx
  test/t8_schemes/t8_gtest_nca.cxx
  test/t8_schemes/t8_gtest_pack_unpack.cxx
  test/t8_schemes/t8_gtest_set_linear_id.cxx
  test/t8_schemes/t8_gtest_successor.cxx
Labels: shouldn't take long, priority: medium

#1424 Fix operator warning
  src/t8_types/t8_operators.hxx
Labels: critical, priority: high, workload: low

#1419 Fix ghost warning
  src/t8_forest/t8_forest_ghost.cxx
Labels: Bug, priority: high, workload: low

#1362 Add corner_face_function
  src/t8_schemes/t8_default/t8_default_hex/t8_default_hex.cxx
  src/t8_schemes/t8_default/t8_default_hex/t8_default_hex.hxx
  src/t8_schemes/t8_default/t8_default_line/t8_default_line.hxx
  src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex.hxx
  test/CMakeLists.txt
  test/t8_schemes/t8_gtest_face_corner.cxx
Labels: workload: low, patch-release

#1307 Update vec
  benchmarks/t8_time_forest_partition.cxx
  example/IO/cmesh/gmsh/t8_load_and_refine_square_w_hole.cxx
  example/IO/forest/netcdf/t8_write_forest_netcdf.cxx
  example/advect/t8_advection.cxx
  example/common/t8_example_common.cxx
  example/common/t8_example_common.hxx
  example/common/t8_example_common_functions.cxx
  example/forest/t8_test_ghost.cxx
  example/remove/t8_example_gauss_blob.cxx
  example/remove/t8_example_spheres.cxx
  src/CMakeLists.txt
  src/Makefile.am
  src/t8_cmesh/t8_cmesh.cxx
  src/t8_cmesh/t8_cmesh_examples.cxx
  src/t8_forest/t8_forest.cxx
  src/t8_geometry/t8_geometry_helpers.c
  src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.cxx
  src/t8_geometry/t8_geometry_implementations/t8_geometry_linear.cxx
  src/t8_geometry/t8_geometry_with_vertices.cxx
  src/t8_types/t8_operators.hxx
  src/t8_types/t8_type.hxx
  src/t8_types/t8_vec.cxx
  src/t8_types/t8_vec.h
  src/t8_types/t8_vec.hxx
  src/t8_vec.h
  src/t8_vtk/t8_vtk_write_ASCII.cxx
  src/t8_vtk/t8_vtk_writer.hxx
  test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_cad.cxx
  test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_lagrange.cxx
  test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_linear.cxx
  test/t8_gtest_custom_assertion.hxx
  test/t8_gtest_eclass.cxx
  test/t8_gtest_vec.cxx
  test/t8_schemes/t8_gtest_element_ref_coords.cxx
  tutorials/general/t8_step3_adapt_forest.cxx
  tutorials/general/t8_step6_stencil.cxx
  tutorials/general/t8_step7_interpolation.cxx
  tutorials/general/t8_tutorial_search.cxx
Labels: enhancement, priority: low, major-release

#1429 Improve CI to a more finegrained CI
  .github/workflows/check_indentation.yml
  .github/workflows/spell_check.yml
  .github/workflows/tests_cmake_testsuite.yml
Labels: CI
