Repository DLR-AMR/t8code, pull requests merged in 2025-03, with the labels that each got.

#1451 also run the CI when a Draft-PR is converted into a PR
  .github/workflows/tests_cmake_testsuite.yml
Labels: CI

#1462 Remove macro checker
  scripts/check_macros.sh
  scripts/pre-commit
Labels: enhancement, priority: high, workload: low

#1482 Documentation: set join orientation
  src/t8_cmesh.h
  src/t8_cmesh/t8_cmesh_types.h
Labels: shouldn't take long, documentation, priority: medium, workload: low

#1345 Standalone scheme face functions
  src/t8_schemes/t8_standalone/t8_standalone_elements.hxx
  src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
  test/t8_forest/t8_gtest_balance.cxx
  test/t8_forest/t8_gtest_element_volume.cxx
  test/t8_forest/t8_gtest_find_owner.cxx
  test/t8_forest/t8_gtest_forest_face_normal.cxx
  test/t8_forest/t8_gtest_half_neighbors.cxx
  test/t8_forest/t8_gtest_partition_data.cxx
  test/t8_forest/t8_gtest_search.cxx
  test/t8_gtest_schemes.hxx
  test/t8_schemes/t8_gtest_boundary_extrude.cxx
  test/t8_schemes/t8_gtest_child_parent_face.cxx
  test/t8_schemes/t8_gtest_face_descendant.cxx
  test/t8_schemes/t8_gtest_face_neigh.cxx
  test/t8_schemes/t8_gtest_input_equal_output.cxx
Labels: New feature

#1490 Bugfix: vtk writer num_cells_to_write [1/3]
  src/t8_vtk/t8_vtk_writer_helper.cxx
Labels: Bug, shouldn't take long, priority: high, workload: low

#1474 Improvement: Dinstinguish internal header files from public ones
  src/CMakeLists.txt
Labels: CMake

#1498 Enhancement: Align standalone to coding guidelines
  src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
Labels: shouldn't take long, priority: low, workload: low

#1506 Fix some typos
  tutorials/features/t8_features_curved_meshes.cxx
Labels: shouldn't take long, Typos, priority: low, workload: low

#1463 Fix syntax in geo files
  tutorials/features/t8_features_curved_meshes_generate_cmesh_tet.geo
  tutorials/features/t8_features_curved_meshes_generate_cmesh_tri.geo
Labels: shouldn't take long, priority: medium, workload: low

#1526 Improvement: Fix a typo
  src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex.cxx
Labels: Typos, priority: high, workload: low
